// GENERATED by scripts/build-osm-snapshots.mjs — OpenStreetMap lifts & pistes bundled per resort (ODbL).
import type { OsmSnapshot } from './types'
import _greek_peak from './greek-peak.json'

export const OSM_SNAPSHOTS: Record<string, OsmSnapshot> = {
  'greek-peak': _greek_peak as unknown as OsmSnapshot,
}
