// GENERATED by scripts/build-osm-snapshots.mjs — OpenStreetMap lifts & pistes bundled per resort (ODbL).
import type { OsmSnapshot } from './types'
import _alpe_d_huez from './alpe-d-huez.json'
import _alta_badia from './alta-badia.json'
import _alta from './alta.json'
import _andermatt_sedrun from './andermatt-sedrun.json'
import _appi_kogen from './appi-kogen.json'
import _are from './are.json'
import _avoriaz from './avoriaz.json'
import _baqueira_beret from './baqueira-beret.json'
import _belleayre from './belleayre.json'
import _big_sky from './big-sky.json'
import _breckenridge from './breckenridge.json'
import _brighton from './brighton.json'
import _bristol_mountain from './bristol-mountain.json'
import _cardrona from './cardrona.json'
import _cervinia from './cervinia.json'
import _chamonix from './chamonix.json'
import _copper_mountain from './copper-mountain.json'
import _coronet_peak from './coronet-peak.json'
import _cortina_d_ampezzo from './cortina-d-ampezzo.json'
import _courchevel from './courchevel.json'
import _courmayeur from './courmayeur.json'
import _crans_montana from './crans-montana.json'
import _davos_klosters from './davos-klosters.json'
import _deer_valley from './deer-valley.json'
import _elk_mountain from './elk-mountain.json'
import _engelberg_titlis from './engelberg-titlis.json'
import _falls_creek from './falls-creek.json'
import _furano from './furano.json'
import _garmisch_partenkirchen from './garmisch-partenkirchen.json'
import _gore_mountain from './gore-mountain.json'
import _grandvalira from './grandvalira.json'
import _greek_peak from './greek-peak.json'
import _grindelwald_wengen from './grindelwald-wengen.json'
import _hakuba_47_goryu from './hakuba-47-goryu.json'
import _hakuba_happo_one from './hakuba-happo-one.json'
import _hintertux_glacier from './hintertux-glacier.json'
import _holiday_valley from './holiday-valley.json'
import _holimont from './holimont.json'
import _hunter_mountain from './hunter-mountain.json'
import _ischgl from './ischgl.json'
import _jackson_hole from './jackson-hole.json'
import _jay_peak from './jay-peak.json'
import _killington from './killington.json'
import _kiroro from './kiroro.json'
import _kitzbuehel from './kitzbuehel.json'
import _kitzsteinhorn from './kitzsteinhorn.json'
import _la_plagne from './la-plagne.json'
import _laax from './laax.json'
import _labrador_mountain from './labrador-mountain.json'
import _les_arcs from './les-arcs.json'
import _les_deux_alpes from './les-deux-alpes.json'
import _livigno from './livigno.json'
import _lotte_arai from './lotte-arai.json'
import _mayrhofen from './mayrhofen.json'
import _megeve from './megeve.json'
import _meribel from './meribel.json'
import _mount_snow from './mount-snow.json'
import _mt_buller from './mt-buller.json'
import _mt_hotham from './mt-hotham.json'
import _mt_hutt from './mt-hutt.json'
import _myoko_suginohara from './myoko-suginohara.json'
import _niseko_united from './niseko-united.json'
import _nozawa_onsen from './nozawa-onsen.json'
import _obergurgl_hochgurgl from './obergurgl-hochgurgl.json'
import _obertauern from './obertauern.json'
import _okemo from './okemo.json'
import _park_city_mountain from './park-city-mountain.json'
import _peek_n_peak from './peek-n-peak.json'
import _perisher from './perisher.json'
import _plattekill from './plattekill.json'
import _rusutsu from './rusutsu.json'
import _saalbach from './saalbach.json'
import _saas_fee from './saas-fee.json'
import _schladming_dachstein from './schladming-dachstein.json'
import _serfaus_fiss_ladis from './serfaus-fiss-ladis.json'
import _serre_chevalier from './serre-chevalier.json'
import _sestriere from './sestriere.json'
import _shiga_kogen from './shiga-kogen.json'
import _ski_arlberg from './ski-arlberg.json'
import _skiwelt from './skiwelt.json'
import _snowbird from './snowbird.json'
import _soelden from './soelden.json'
import _solitude from './solitude.json'
import _song_mountain from './song-mountain.json'
import _st_moritz from './st-moritz.json'
import _steamboat from './steamboat.json'
import _stowe from './stowe.json'
import _stubai_glacier from './stubai-glacier.json'
import _sugarbush from './sugarbush.json'
import _swain from './swain.json'
import _the_remarkables from './the-remarkables.json'
import _thredbo from './thredbo.json'
import _tignes from './tignes.json'
import _titus_mountain from './titus-mountain.json'
import _toggenburg from './toggenburg.json'
import _treble_cone from './treble-cone.json'
import _vail from './vail.json'
import _val_d_isere from './val-d-isere.json'
import _val_gardena from './val-gardena.json'
import _val_thorens from './val-thorens.json'
import _verbier from './verbier.json'
import _west_mountain from './west-mountain.json'
import _whistler_blackcomb from './whistler-blackcomb.json'
import _whiteface from './whiteface.json'
import _windham_mountain from './windham-mountain.json'
import _zao_onsen from './zao-onsen.json'
import _zermatt from './zermatt.json'

export const OSM_SNAPSHOTS: Record<string, OsmSnapshot> = {
  'alpe-d-huez': _alpe_d_huez as unknown as OsmSnapshot,
  'alta-badia': _alta_badia as unknown as OsmSnapshot,
  'alta': _alta as unknown as OsmSnapshot,
  'andermatt-sedrun': _andermatt_sedrun as unknown as OsmSnapshot,
  'appi-kogen': _appi_kogen as unknown as OsmSnapshot,
  'are': _are as unknown as OsmSnapshot,
  'avoriaz': _avoriaz as unknown as OsmSnapshot,
  'baqueira-beret': _baqueira_beret as unknown as OsmSnapshot,
  'belleayre': _belleayre as unknown as OsmSnapshot,
  'big-sky': _big_sky as unknown as OsmSnapshot,
  'breckenridge': _breckenridge as unknown as OsmSnapshot,
  'brighton': _brighton as unknown as OsmSnapshot,
  'bristol-mountain': _bristol_mountain as unknown as OsmSnapshot,
  'cardrona': _cardrona as unknown as OsmSnapshot,
  'cervinia': _cervinia as unknown as OsmSnapshot,
  'chamonix': _chamonix as unknown as OsmSnapshot,
  'copper-mountain': _copper_mountain as unknown as OsmSnapshot,
  'coronet-peak': _coronet_peak as unknown as OsmSnapshot,
  'cortina-d-ampezzo': _cortina_d_ampezzo as unknown as OsmSnapshot,
  'courchevel': _courchevel as unknown as OsmSnapshot,
  'courmayeur': _courmayeur as unknown as OsmSnapshot,
  'crans-montana': _crans_montana as unknown as OsmSnapshot,
  'davos-klosters': _davos_klosters as unknown as OsmSnapshot,
  'deer-valley': _deer_valley as unknown as OsmSnapshot,
  'elk-mountain': _elk_mountain as unknown as OsmSnapshot,
  'engelberg-titlis': _engelberg_titlis as unknown as OsmSnapshot,
  'falls-creek': _falls_creek as unknown as OsmSnapshot,
  'furano': _furano as unknown as OsmSnapshot,
  'garmisch-partenkirchen': _garmisch_partenkirchen as unknown as OsmSnapshot,
  'gore-mountain': _gore_mountain as unknown as OsmSnapshot,
  'grandvalira': _grandvalira as unknown as OsmSnapshot,
  'greek-peak': _greek_peak as unknown as OsmSnapshot,
  'grindelwald-wengen': _grindelwald_wengen as unknown as OsmSnapshot,
  'hakuba-47-goryu': _hakuba_47_goryu as unknown as OsmSnapshot,
  'hakuba-happo-one': _hakuba_happo_one as unknown as OsmSnapshot,
  'hintertux-glacier': _hintertux_glacier as unknown as OsmSnapshot,
  'holiday-valley': _holiday_valley as unknown as OsmSnapshot,
  'holimont': _holimont as unknown as OsmSnapshot,
  'hunter-mountain': _hunter_mountain as unknown as OsmSnapshot,
  'ischgl': _ischgl as unknown as OsmSnapshot,
  'jackson-hole': _jackson_hole as unknown as OsmSnapshot,
  'jay-peak': _jay_peak as unknown as OsmSnapshot,
  'killington': _killington as unknown as OsmSnapshot,
  'kiroro': _kiroro as unknown as OsmSnapshot,
  'kitzbuehel': _kitzbuehel as unknown as OsmSnapshot,
  'kitzsteinhorn': _kitzsteinhorn as unknown as OsmSnapshot,
  'la-plagne': _la_plagne as unknown as OsmSnapshot,
  'laax': _laax as unknown as OsmSnapshot,
  'labrador-mountain': _labrador_mountain as unknown as OsmSnapshot,
  'les-arcs': _les_arcs as unknown as OsmSnapshot,
  'les-deux-alpes': _les_deux_alpes as unknown as OsmSnapshot,
  'livigno': _livigno as unknown as OsmSnapshot,
  'lotte-arai': _lotte_arai as unknown as OsmSnapshot,
  'mayrhofen': _mayrhofen as unknown as OsmSnapshot,
  'megeve': _megeve as unknown as OsmSnapshot,
  'meribel': _meribel as unknown as OsmSnapshot,
  'mount-snow': _mount_snow as unknown as OsmSnapshot,
  'mt-buller': _mt_buller as unknown as OsmSnapshot,
  'mt-hotham': _mt_hotham as unknown as OsmSnapshot,
  'mt-hutt': _mt_hutt as unknown as OsmSnapshot,
  'myoko-suginohara': _myoko_suginohara as unknown as OsmSnapshot,
  'niseko-united': _niseko_united as unknown as OsmSnapshot,
  'nozawa-onsen': _nozawa_onsen as unknown as OsmSnapshot,
  'obergurgl-hochgurgl': _obergurgl_hochgurgl as unknown as OsmSnapshot,
  'obertauern': _obertauern as unknown as OsmSnapshot,
  'okemo': _okemo as unknown as OsmSnapshot,
  'park-city-mountain': _park_city_mountain as unknown as OsmSnapshot,
  'peek-n-peak': _peek_n_peak as unknown as OsmSnapshot,
  'perisher': _perisher as unknown as OsmSnapshot,
  'plattekill': _plattekill as unknown as OsmSnapshot,
  'rusutsu': _rusutsu as unknown as OsmSnapshot,
  'saalbach': _saalbach as unknown as OsmSnapshot,
  'saas-fee': _saas_fee as unknown as OsmSnapshot,
  'schladming-dachstein': _schladming_dachstein as unknown as OsmSnapshot,
  'serfaus-fiss-ladis': _serfaus_fiss_ladis as unknown as OsmSnapshot,
  'serre-chevalier': _serre_chevalier as unknown as OsmSnapshot,
  'sestriere': _sestriere as unknown as OsmSnapshot,
  'shiga-kogen': _shiga_kogen as unknown as OsmSnapshot,
  'ski-arlberg': _ski_arlberg as unknown as OsmSnapshot,
  'skiwelt': _skiwelt as unknown as OsmSnapshot,
  'snowbird': _snowbird as unknown as OsmSnapshot,
  'soelden': _soelden as unknown as OsmSnapshot,
  'solitude': _solitude as unknown as OsmSnapshot,
  'song-mountain': _song_mountain as unknown as OsmSnapshot,
  'st-moritz': _st_moritz as unknown as OsmSnapshot,
  'steamboat': _steamboat as unknown as OsmSnapshot,
  'stowe': _stowe as unknown as OsmSnapshot,
  'stubai-glacier': _stubai_glacier as unknown as OsmSnapshot,
  'sugarbush': _sugarbush as unknown as OsmSnapshot,
  'swain': _swain as unknown as OsmSnapshot,
  'the-remarkables': _the_remarkables as unknown as OsmSnapshot,
  'thredbo': _thredbo as unknown as OsmSnapshot,
  'tignes': _tignes as unknown as OsmSnapshot,
  'titus-mountain': _titus_mountain as unknown as OsmSnapshot,
  'toggenburg': _toggenburg as unknown as OsmSnapshot,
  'treble-cone': _treble_cone as unknown as OsmSnapshot,
  'vail': _vail as unknown as OsmSnapshot,
  'val-d-isere': _val_d_isere as unknown as OsmSnapshot,
  'val-gardena': _val_gardena as unknown as OsmSnapshot,
  'val-thorens': _val_thorens as unknown as OsmSnapshot,
  'verbier': _verbier as unknown as OsmSnapshot,
  'west-mountain': _west_mountain as unknown as OsmSnapshot,
  'whistler-blackcomb': _whistler_blackcomb as unknown as OsmSnapshot,
  'whiteface': _whiteface as unknown as OsmSnapshot,
  'windham-mountain': _windham_mountain as unknown as OsmSnapshot,
  'zao-onsen': _zao_onsen as unknown as OsmSnapshot,
  'zermatt': _zermatt as unknown as OsmSnapshot,
}
