/* ===================== Views: buyers, money map ===================== */
const SERVICE_ORDER = ['joint', 'army', 'daf', 'navy', 'space'];
const SERVICE_LABEL = { joint: 'Joint / OSD', army: 'Army', daf: 'Air Force', navy: 'Navy & Marine Corps', space: 'Space Force' };
const ORG_LAYERS = ['user', 'requirement', 'program', 'contracting', 'budget', 'lab', 'innovation', 'policy'];
const ORG_LABEL = { user: 'Users', requirement: 'Requirement owners', program: 'Program offices', contracting: 'Contracting offices', budget: 'Budget & money', lab: 'Labs', innovation: 'Innovation units', policy: 'Policy & oversight' };
const orgGraph = (g) => flowDiagram(arr(g.nodes).map((n) => ({ ...n })), arr(g.edges), { layers: ORG_LAYERS, layerOf: (n) => n.type, layerLabel: (k) => ORG_LABEL[k] || titleCase(k) });
const chainList = (chains) => (arr(chains).length ? h('div', { class: 'pipe-list' }, arr(chains).map(chainPipeline)) : empty('No buying chains recorded.'));

route('buyers', (r) => {
  const svc = SERVICE_ORDER.includes(r.id) ? r.id : 'army';
  const b = D.buyers?.[svc] || {};
  const mm = D.money?.buyer_map || {};
  const bar = h('div', { class: 'tabs' }, SERVICE_ORDER.map((k) => h('button', { class: k === svc ? 'active' : '', onclick: () => (location.hash = '#buyers/' + k) }, SERVICE_LABEL[k])));
  const orgChart = arr(b.org_chart?.nodes).length ? orgGraph(b.org_chart) : empty('No org chart recorded.');
  const tabDefs = [
    { title: 'Organizations', render: () => h('div', { class: 'stack' }, card('Organization chart', P('Rows run from the people who use the systems, through who writes the requirement, who manages the program and who signs the contract, to where the money sits. Labs, innovation units and policy bodies sit in the lower rows. Hover a box to trace its links.'), orgChart), card('Organizations (' + arr(b.organizations).length + ')', dataTable(arr(b.organizations), [{ key: 'name', title: 'Organization', render: (o) => h('div', null, h('b', null, o.name), o.acronym ? h('span', { class: 'cell-sub' }, o.acronym + (o.parent ? ' · under ' + o.parent : '')) : null) }, { key: 'role', title: 'Role', render: (o) => chip(o.role || '—', 'outline') }, { key: 'portfolio', title: 'Portfolio' }, { key: 'current_status_2026', title: 'Status (2026)' }, { key: 'startup_relevance', title: 'Startup relevance' }, { key: 'source_url', title: 'Source', render: (o) => h('div', null, o.source_url ? h('a', { href: o.source_url, target: '_blank', rel: 'noopener' }, shortUrl(o.source_url)) : '—', confTag(o.confidence)) }], { facets: [{ title: 'Role', get: (o) => o.role }], id: 'orgs-' + svc }))) },
    { title: 'Programs', render: () => card('Programs and budget lines', dataTable(arr(b.programs), [{ key: 'name', title: 'Program', render: (p) => h('div', null, h('b', null, p.name), p.owner ? h('span', { class: 'cell-sub' }, p.owner) : null) }, { key: 'description', title: 'What it is' }, { key: 'status_2026', title: 'Status (2026)' }, { key: 'vendors', title: 'Vendors', render: (p) => chips(p.vendors) }, { key: 'budget', title: 'Budget line', render: (p) => { const bd = p.budget || {}; return h('div', null, bd.pe_number_or_line ? h('span', { class: 'mono' }, bd.pe_number_or_line) : '—', h('span', { class: 'cell-sub' }, [bd.appropriation, bd.fy26_request ? 'FY26 ' + bd.fy26_request : null, bd.fy27_request ? 'FY27 ' + bd.fy27_request : null].filter(Boolean).join(' · ')), bd.source_url ? h('a', { class: 'small', href: bd.source_url, target: '_blank', rel: 'noopener' }, 'source') : null); } }, { key: 'third_party_software_openness', title: 'Third-party software?' }, { key: 'contract_evidence', title: 'Contracts', render: (p) => (arr(p.contract_evidence).length ? fold(arr(p.contract_evidence).length + ' contract(s)', contractTable(p.contract_evidence, { showVendor: true })) : '—') }], { id: 'programs-' + svc })) },
    { title: 'Pathways', render: () => card('Procurement pathways for a new company', dataTable(arr(b.procurement_pathways), [{ key: 'pathway', title: 'Pathway', render: (p) => h('b', null, p.pathway) }, { key: 'how_it_works_here', title: 'How it works here' }, { key: 'typical_award_size', title: 'Typical award' }, { key: 'timeline', title: 'Timeline' }, { key: 'fit_for_two_founder_startup', title: 'Fit for two founders' }, { key: 'eligibility_notes', title: 'Eligibility notes' }, { key: 'recent_examples', title: 'Recent examples', render: (p) => (arr(p.recent_examples).length ? h('ul', { class: 'small' }, arr(p.recent_examples).map((e) => h('li', null, e.company + ': ' + (e.what || '') + (e.amount ? ' (' + e.amount + ')' : '') + (e.date ? ', ' + e.date : ''), e.source_url ? [' ', h('a', { href: e.source_url, target: '_blank', rel: 'noopener' }, '↗')] : null))) : '—') }], { filterable: false })) },
    { title: 'Buying chains', render: () => card(h('div', { class: 'card-head' }, h('h3', null, 'Buying chains: from the user to the budget line'), h('span', { class: 'small muted' }, arr(b.chains).length + ' chains')), P('Each chain reads top to bottom in seven steps, from the soldier or officer with the problem to the companies already being paid.'), chainLegend(), chainList(b.chains)) },
    { title: 'How a startup gets in', render: () => h('div', { class: 'stack' }, card('How a startup gets in', isStr(b.how_a_startup_gets_in) ? rich(b.how_a_startup_gets_in, { limit: 8 }) : val(b.how_a_startup_gets_in)), arr(b.recent_changes).length ? card('Recent organizational changes', evidenceList(arr(b.recent_changes).map((c) => ({ claim: c.change, pub_date: c.date, source_url: c.source_url })))) : null, b.saturation_statement ? card('Saturation statement', rich(b.saturation_statement)) : null, sourceList(b.sources)) },
  ];
  const ranked = arr(mm.ranked_entry_pathways);
  return h('div', { class: 'page' },
    pageHead('Deliverable 3 · Government buyer map', 'Who uses, sponsors, buys and funds C4ISR software', 'For every service: the current (2026) organizations, programs and budget lines, the realistic procurement pathways, and the chain from user to budget. Organizations were renamed and merged repeatedly in 2024–2026; each entry cites the source used to confirm its current name.'),
    ranked.length ? card('Ranked entry pathways for this founding team (cross-service)', h('ol', { class: 'path-rank' }, ranked.map((p, i) => h('li', { style: { '--i': i } }, h('div', { class: 'pr-n' }, String(i + 1)), h('div', { class: 'pr-body' }, h('b', null, p.pathway), rich(p.why, { limit: 2, threshold: 180 }), p.eligibility_caveat ? h('div', { class: 'pr-caveat' }, h('span', { class: 'eyebrow' }, 'Caveat'), ' ', inline(p.eligibility_caveat)) : null))))) : null,
    bar, b.service ? h('h2', null, b.service) : null, tabs(tabDefs, tabIndexFor(tabDefs, r.sub)));
});

const FAIL_LABEL = { 'BROKEN-REQUIREMENT': 'No requirement owner', 'BROKEN-PROGRAM': 'No program office', 'OCCUPIED-BY-DESIGNATION': 'Slot assigned to an incumbent', 'BROKEN-BUDGET': 'No budget line', 'NON-DOD-BUYER': 'Buyer is outside DoD', OCCUPIED: 'Incumbents already paid', INACCESSIBLE: 'Legally closed to this team', 'CLOSED-WINDOW': 'Solicitation window closed' };
function moneyPipeline(c) {
  return h('ol', { class: 'pipe-steps' }, arr(c.links).map((l) => {
    let v = String(l.value || ''); const tag = (v.match(/^\s*\[([A-Z ]+)\]\s*/) || [])[1];
    if (tag) v = v.replace(/^\s*\[[A-Z ]+\]\s*/, '');
    const conf = String(l.confidence || '').toUpperCase();
    const label = titleCase(String(l.link || '').split(' (')[0].toLowerCase());
    return h('li', { class: 'pipe-step' + (tag ? ' broken' : conf.startsWith('LOW') ? ' weak' : '') },
      h('div', { class: 'pipe-label' }, h('span', { class: 'pipe-n' }, tag ? '!' : '✓'), label),
      h('div', { class: 'pipe-val' }, tag ? h('span', { class: 'chip bad' }, titleCase(tag.toLowerCase())) : null, v ? rich(v, { limit: 2, threshold: 170 }) : h('span', { class: 'empty' }, '—'), h('div', { class: 'pipe-src' }, conf ? confTag(conf) : null, l.source_url ? h('a', { href: l.source_url, target: '_blank', rel: 'noopener' }, shortUrl(l.source_url)) : null)));
  }));
}
route('money', (r) => {
  const mm = D.money || {};
  const chains = arr(mm.chains);
  const stages = arr(mm.procurement_stages);
  const ppg = arr(mm.proto_purgatory);
  const unified = mm.buyer_map?.org_chart;
  const gapTitle = (id) => (D.registry?.gaps || []).find((g) => g.id === id)?.title || id;
  const withPath = chains.filter((c) => c.has_path);
  const countBy = (list, f) => { const m = {}; list.forEach((x) => { const k = f(x); if (k) m[k] = (m[k] || 0) + 1; }); return Object.entries(m).sort((a, b) => b[1] - a[1]); };
  const weak = countBy(chains.filter((c) => !c.has_path), (c) => titleCase(String(c.weakest_link || '').toLowerCase()));
  const modes = countBy(chains, (c) => FAIL_LABEL[c.failure_mode] || titleCase(String(c.failure_mode || '').toLowerCase()));
  const stageCount = countBy(stages, (s) => s.stage);
  const sorted = chains.slice().sort((a, b) => (b.has_path === true) - (a.has_path === true) || String(a.gap_id).localeCompare(String(b.gap_id)));
  const chainFold = (c, open) => fold(h('span', { class: 'mf-sum' }, h('span', { class: 'mono muted' }, c.gap_id), h('span', { class: 'mf-title' }, gapTitle(c.gap_id)), c.has_path ? chip('Path identified', 'good') : chip(FAIL_LABEL[c.failure_mode] || 'No identifiable path', 'bad')),
    [c.penalty ? h('div', { class: 'callout amber' }, h('div', { class: 'eyebrow' }, 'Penalty'), rich(c.penalty, { limit: 3 })) : null, c.weakest_link ? h('p', { class: 'small' }, h('b', null, 'Weakest link: '), titleCase(String(c.weakest_link).toLowerCase())) : null, moneyPipeline(c), h('p', { class: 'small' }, h('a', { href: '#gaps/' + c.gap_id }, 'Open the gap card →'))], open);
  return h('div', { class: 'page' },
    pageHead('Deliverable · Money map', 'From problem to budget', 'For every registry gap: who has the problem, who owns the requirement, which program office and contracting office can act, where the money sits, which vehicle applies, and who is already being paid. A gap with no identifiable path receives a major penalty.'),
    chains.length ? h('div', { class: 'kpis' }, kpi(chains.length, 'gaps traced to the budget'), kpi(withPath.length, 'have a path a new company could use'), kpi(chains.length - withPath.length, 'have no identifiable path'), weak[0] ? kpi(weak[0][1], 'break first at the ' + weak[0][0].toLowerCase()) : null) : null,
    mm.summary ? card('What the money map says', rich(String(mm.summary).replace(/^MONEY MAP \(Phase \d+\):\s*/i, ''), { limit: 6 })) : (chains.length ? null : h('div', { class: 'callout amber' }, P('Stage status: per-gap money maps are produced in the synthesis stage. Below are the buying chains documented per service in the buyer maps, which the gap-level chains build on.'))),
    chains.length ? h('div', { class: 'grid cols-2' },
      card('Where the chain breaks', P('For the ' + (chains.length - withPath.length) + ' gaps with no path, the first link that fails.'), scoreBars(weak.map(([k, n]) => ({ label: k, value: n })), Math.max(...weak.map((x) => x[1])))),
      card('Why there is no door', P('The failure mode behind each of the ' + chains.length + ' chains.'), scoreBars(modes.map(([k, n]) => ({ label: k, value: n, warn: /closed|incumbent|occupied/i.test(k) })), Math.max(...modes.map((x) => x[1]))))) : null,
    chains.length ? null : card('Buying chains by service', chainLegend(), h('div', { class: 'stack' }, SERVICE_ORDER.filter((k) => D.buyers?.[k]).map((k) => fold(SERVICE_LABEL[k] + ' (' + arr(D.buyers[k].chains).length + ' chains)', chainList(D.buyers[k].chains), k === 'army')))),
    chains.length ? card(h('div', { class: 'card-head' }, h('h3', null, 'Chains by gap'), h('span', { class: 'small muted' }, 'Gaps with a path first')), h('div', { class: 'pipe-legend' }, h('span', null, h('span', { class: 'pipe-n' }, '✓'), ' link identified'), h('span', { class: 'pipe-step broken', style: { display: 'inline', padding: 0 } }, h('span', { class: 'pipe-n' }, '!')), h('span', null, ' link broken, occupied or closed')), h('div', { class: 'fold-list money-folds' }, sorted.map((c, i) => chainFold(c, i === 0)))) : null,
    stages.length ? card('Procurement signal stage by gap', stageCount.length ? h('div', { class: 'chips', style: { marginBottom: '10px' } }, stageCount.map(([k, n]) => h('span', null, stageChip(k), ' ', h('b', null, n)))) : null, dataTable(stages, [{ key: 'gap_id', title: 'Gap', render: (s) => h('a', { href: '#gaps/' + s.gap_id }, s.gap_id + ' ' + gapTitle(s.gap_id)) }, { key: 'stage', title: 'Stage', render: (s) => stageChip(s.stage) }, { key: 'rationale', title: 'Rationale' }, { key: 'evidence', title: 'Signals', render: (s) => (arr(s.evidence).length ? fold(arr(s.evidence).length + ' signal(s)', timeline(s.evidence)) : '—') }], { filterable: true, facets: [{ title: 'Stage', get: (s) => s.stage }], id: 'procstages' })) : null,
    ppg.length ? card('Proto-purgatory: do pilots in this theme ever reach production?', h('div', { class: 'rec-grid ppg-grid' }, ppg.map((p, i) => h('article', { class: 'rec ppg v-' + (/opport/i.test(p.verdict) ? 'good' : /warn/i.test(p.verdict) ? 'bad' : 'mixed'), style: { '--i': i } }, h('div', { class: 'rec-title' }, p.theme, ' ', chip(p.verdict || '—', /opport/i.test(p.verdict) ? 'good' : /warn/i.test(p.verdict) ? 'bad' : 'warn')), p.rationale ? rich(p.rationale, { limit: 2, threshold: 180 }) : null, p.evidence ? fold('Evidence', rich(p.evidence, { limit: 6 })) : null, arr(p.gap_ids).length ? h('div', { class: 'chips' }, arr(p.gap_ids).map((g) => h('a', { class: 'chip mono', href: '#gaps/' + g }, g))) : null)))) : null,
    unified && arr(unified.nodes).length ? card('Unified buyer org chart', P('All five services on one chart. Hover a box to trace who it answers to and who it pays.'), orgGraph(unified)) : null,
    arr(mm.buyer_map?.services).length ? card('Cross-service summary', h('div', { class: 'grid cols-2' }, arr(mm.buyer_map.services).map((s) => h('div', { class: 'stack svc-sum' }, h('h3', null, s.service), h('div', { class: 'eyebrow' }, 'Key organizations'), h('ul', { class: 'rt-list' }, arr(s.key_orgs).map((o) => h('li', null, h('b', null, o.name), o.role ? ' (' + o.role + ')' : '', o.note ? [': ', ...inline(o.note)] : ''))), h('div', { class: 'eyebrow' }, 'Programs'), h('ul', { class: 'rt-list' }, arr(s.programs).map((p) => h('li', null, h('b', null, p.name), p.why_relevant ? [': ', ...inline(p.why_relevant)] : '', p.budget_line ? h('span', { class: 'muted' }, ' · ' + p.budget_line) : null))), h('div', { class: 'eyebrow' }, 'Pathways'), h('ul', { class: 'rt-list' }, arr(s.pathways).map((p) => h('li', null, h('b', null, p.pathway), p.fit ? [': ', ...inline(p.fit)] : '', p.caveat ? h('span', { class: 'muted' }, ' · ' + p.caveat) : null))))))) : null,
    mm.method_notes ? fold('Method notes', isStr(mm.method_notes) ? rich(mm.method_notes) : infoGrid(Object.entries(mm.method_notes).map(([k, v]) => [titleCase(k), Array.isArray(v) ? v.join(', ') : v]))) : null,
    sourceList(mm.sources));
});
