/* ===================== Views: buyers, money map ===================== */
const SERVICE_ORDER = ['joint', 'army', 'daf', 'navy', 'space'];
const SERVICE_LABEL = { joint: 'Joint / OSD', army: 'Army', daf: 'Air Force', navy: 'Navy & Marine Corps', space: 'Space Force' };

route('buyers', (r) => {
  const svc = SERVICE_ORDER.includes(r.id) ? r.id : 'army';
  const b = D.buyers?.[svc] || {};
  const mm = D.money?.buyer_map || {};
  const bar = h('div', { class: 'tabs' }, SERVICE_ORDER.map((k) => h('button', { class: k === svc ? 'active' : '', onclick: () => (location.hash = '#buyers/' + k) }, SERVICE_LABEL[k])));
  const orgChart = arr(b.org_chart?.nodes).length ? layeredGraph(arr(b.org_chart.nodes).map((n) => ({ ...n })), arr(b.org_chart.edges), { layers: ['user', 'requirement', 'program', 'contracting', 'budget', 'lab', 'innovation', 'policy'], layerOf: (n) => n.type, nodeW: 168, nodeH: 56, gapX: 52, gapY: 10, label: SERVICE_LABEL[svc] + ' organization chart' }) : empty('No org chart recorded.');
  const tabDefs = [
    { title: 'Organizations', render: () => h('div', { class: 'stack' }, card('Organization chart: user → requirement owner → program office → contracting → budget', h('p', { class: 'small muted' }, 'Hover a node to highlight its relationships. Labs, innovation organizations and policy bodies are shown as additional columns.'), orgChart), card('Organizations (' + arr(b.organizations).length + ')', dataTable(arr(b.organizations), [{ key: 'name', title: 'Organization', render: (o) => h('div', null, h('b', null, o.name), o.acronym ? h('span', { class: 'cell-sub' }, o.acronym + (o.parent ? ' · under ' + o.parent : '')) : null) }, { key: 'role', title: 'Role', render: (o) => chip(o.role || '—', 'outline') }, { key: 'portfolio', title: 'Portfolio' }, { key: 'current_status_2026', title: 'Status (2026)' }, { key: 'startup_relevance', title: 'Startup relevance' }, { key: 'source_url', title: 'Source', render: (o) => h('div', null, o.source_url ? h('a', { href: o.source_url, target: '_blank', rel: 'noopener' }, shortUrl(o.source_url)) : '—', confTag(o.confidence)) }], { facets: [{ title: 'Role', get: (o) => o.role }], id: 'orgs-' + svc }))) },
    { title: 'Programs', render: () => card('Programs and budget lines', dataTable(arr(b.programs), [{ key: 'name', title: 'Program', render: (p) => h('div', null, h('b', null, p.name), p.owner ? h('span', { class: 'cell-sub' }, p.owner) : null) }, { key: 'description', title: 'What it is' }, { key: 'status_2026', title: 'Status (2026)' }, { key: 'vendors', title: 'Vendors', render: (p) => chips(p.vendors) }, { key: 'budget', title: 'Budget line', render: (p) => { const bd = p.budget || {}; return h('div', null, bd.pe_number_or_line ? h('span', { class: 'mono' }, bd.pe_number_or_line) : '—', h('span', { class: 'cell-sub' }, [bd.appropriation, bd.fy26_request ? 'FY26 ' + bd.fy26_request : null, bd.fy27_request ? 'FY27 ' + bd.fy27_request : null].filter(Boolean).join(' · ')), bd.source_url ? h('a', { class: 'small', href: bd.source_url, target: '_blank', rel: 'noopener' }, 'source') : null); } }, { key: 'third_party_software_openness', title: 'Third-party software?' }, { key: 'contract_evidence', title: 'Contracts', render: (p) => (arr(p.contract_evidence).length ? fold(arr(p.contract_evidence).length + ' contract(s)', contractTable(p.contract_evidence, { showVendor: true })) : '—') }], { id: 'programs-' + svc })) },
    { title: 'Pathways', render: () => card('Procurement pathways for a new company', dataTable(arr(b.procurement_pathways), [{ key: 'pathway', title: 'Pathway', render: (p) => h('b', null, p.pathway) }, { key: 'how_it_works_here', title: 'How it works here' }, { key: 'typical_award_size', title: 'Typical award' }, { key: 'timeline', title: 'Timeline' }, { key: 'fit_for_two_founder_startup', title: 'Fit for two founders' }, { key: 'eligibility_notes', title: 'Eligibility notes' }, { key: 'recent_examples', title: 'Recent examples', render: (p) => (arr(p.recent_examples).length ? h('ul', { class: 'small' }, arr(p.recent_examples).map((e) => h('li', null, e.company + ': ' + (e.what || '') + (e.amount ? ' (' + e.amount + ')' : '') + (e.date ? ', ' + e.date : ''), e.source_url ? [' ', h('a', { href: e.source_url, target: '_blank', rel: 'noopener' }, '↗')] : null))) : '—') }], { filterable: false })) },
    { title: 'Buying chains', render: () => card('Problem → user → requirement owner → program office → contracting → budget', dataTable(arr(b.chains), [{ key: 'problem_area', title: 'Problem area', render: (c) => h('b', null, c.problem_area) }, { key: 'user', title: 'User' }, { key: 'requirement_owner', title: 'Requirement owner' }, { key: 'program_office', title: 'Program office' }, { key: 'contracting_office', title: 'Contracting office' }, { key: 'budget_line', title: 'Budget line' }, { key: 'contract_vehicle', title: 'Vehicle' }, { key: 'current_vendors', title: 'Current vendors', render: (c) => chips(c.current_vendors) }, { key: 'confidence', title: 'Conf.', render: (c) => confTag(c.confidence) || '—' }], { filterable: false })) },
    { title: 'How a startup gets in', render: () => h('div', { class: 'stack' }, card('How a startup gets in', h('div', { class: 'prose' }, val(b.how_a_startup_gets_in))), arr(b.recent_changes).length ? card('Recent organizational changes', evidenceList(arr(b.recent_changes).map((c) => ({ claim: c.change, pub_date: c.date, source_url: c.source_url })))) : null, b.saturation_statement ? card('Saturation statement', h('p', null, b.saturation_statement)) : null, sourceList(b.sources)) },
  ];
  const ranked = arr(mm.ranked_entry_pathways);
  return h('div', { class: 'page' },
    pageHead('Deliverable 3 · Government buyer map', 'Who uses, sponsors, buys and funds C4ISR software', 'For every service: the current (2026) organizations, programs and budget lines, the realistic procurement pathways, and the chain from user to budget. Organizations were renamed and merged repeatedly in 2024–2026; each entry cites the source used to confirm its current name.'),
    ranked.length ? card('Ranked entry pathways for this founding team (cross-service)', h('ol', null, ranked.map((p) => h('li', null, h('b', null, p.pathway), ' — ', p.why, p.eligibility_caveat ? h('span', { class: 'muted' }, ' Caveat: ' + p.eligibility_caveat) : null)))) : null,
    bar, b.service ? h('h2', null, b.service) : null, tabs(tabDefs, tabIndexFor(tabDefs, r.sub)));
});

route('money', (r) => {
  const mm = D.money || {};
  const chains = arr(mm.chains);
  const stages = arr(mm.procurement_stages);
  const ppg = arr(mm.proto_purgatory);
  const unified = mm.buyer_map?.org_chart;
  const gapTitle = (id) => (D.registry?.gaps || []).find((g) => g.id === id)?.title || id;
  const LINKS = ['problem', 'user', 'requirement_owner', 'program_office', 'contracting_office', 'budget', 'contract_vehicle', 'current_vendors'];
  return h('div', { class: 'page' },
    pageHead('Deliverable · Money map', 'From problem to budget', 'For every registry gap: who has the problem, who owns the requirement, which program office and contracting office can act, where the money sits (appropriation and program element), which vehicle applies, and who is already being paid. A gap with no identifiable path receives a major penalty.'),
    mm.summary ? h('div', { class: 'callout' }, h('p', null, mm.summary)) : null,
    card('Chains by gap (' + chains.length + ')', h('p', { class: 'small muted' }, 'Border color marks the confidence of each link: green high, amber medium, red low.'), h('div', { class: 'stack' }, chains.map((c) => fold(h('span', null, h('span', { class: 'mono muted' }, c.gap_id + ' '), gapTitle(c.gap_id), ' ', c.has_path === false ? chip('No identifiable path', 'bad') : chip('Path identified', 'good'), c.penalty ? chip('Penalty: ' + c.penalty, 'warn') : null), h('div', { class: 'stack' }, h('div', { class: 'money-chain' }, LINKS.map((k) => { const l = arr(c.links).find((x) => x.link === k) || {}; return h('div', { class: 'money-link conf-' + String(l.confidence || '').toUpperCase() }, h('div', { class: 'ml-key' }, titleCase(k)), h('div', { class: 'ml-val' }, l.value || '—'), l.detail ? h('div', { class: 'ml-det' }, l.detail) : null, l.source_url ? h('a', { class: 'small', href: l.source_url, target: '_blank', rel: 'noopener' }, shortUrl(l.source_url)) : null); })), c.weakest_link ? h('p', { class: 'small' }, h('b', null, 'Weakest link: '), c.weakest_link) : null, h('p', { class: 'small' }, h('a', { href: '#gaps/' + c.gap_id }, 'Open gap card →'))))))),
    h('div', { class: 'grid cols-2' },
      card('Procurement signal stage by gap', stages.length ? dataTable(stages, [{ key: 'gap_id', title: 'Gap', render: (s) => h('a', { href: '#gaps/' + s.gap_id }, s.gap_id + ' ' + gapTitle(s.gap_id)) }, { key: 'stage', title: 'Stage', render: (s) => stageChip(s.stage) }, { key: 'rationale', title: 'Rationale' }, { key: 'evidence', title: 'Signals', render: (s) => (arr(s.evidence).length ? fold(arr(s.evidence).length + ' signal(s)', timeline(s.evidence)) : '—') }], { filterable: false }) : empty()),
      card('Proto-purgatory verdicts', ppg.length ? h('div', { class: 'stack' }, ppg.map((p) => h('div', { class: 'ev-item' }, h('div', { class: 'ev-head' }, h('b', null, p.theme), chip(p.verdict || '—', /opport/i.test(p.verdict) ? 'good' : /warn/i.test(p.verdict) ? 'bad' : 'warn')), h('div', { class: 'small' }, p.evidence), h('div', { class: 'small muted' }, p.rationale), arr(p.gap_ids).length ? h('div', { class: 'chips' }, arr(p.gap_ids).map((g) => h('a', { class: 'chip mono', href: '#gaps/' + g }, g))) : null))) : empty())),
    unified && arr(unified.nodes).length ? card('Unified buyer org chart', layeredGraph(arr(unified.nodes), arr(unified.edges), { layers: ['user', 'requirement', 'program', 'contracting', 'budget', 'lab', 'innovation', 'policy'], layerOf: (n) => n.type, nodeW: 168, nodeH: 56, gapX: 52, gapY: 10, label: 'Unified buyer org chart' })) : null,
    arr(mm.buyer_map?.services).length ? card('Cross-service summary', h('div', { class: 'grid cols-2' }, arr(mm.buyer_map.services).map((s) => h('div', { class: 'stack' }, h('h3', null, s.service), h('div', { class: 'eyebrow' }, 'Key organizations'), h('ul', { class: 'small' }, arr(s.key_orgs).map((o) => h('li', null, h('b', null, o.name), o.role ? ' (' + o.role + ')' : '', o.note ? ': ' + o.note : ''))), h('div', { class: 'eyebrow' }, 'Programs'), h('ul', { class: 'small' }, arr(s.programs).map((p) => h('li', null, h('b', null, p.name), p.why_relevant ? ': ' + p.why_relevant : '', p.budget_line ? h('span', { class: 'muted' }, ' · ' + p.budget_line) : null, p.openness_to_third_party_software ? h('span', { class: 'muted' }, ' · 3rd-party software: ' + p.openness_to_third_party_software) : null))), h('div', { class: 'eyebrow' }, 'Pathways'), h('ul', { class: 'small' }, arr(s.pathways).map((p) => h('li', null, h('b', null, p.pathway), p.fit ? ': ' + p.fit : '', p.caveat ? h('span', { class: 'muted' }, ' · ' + p.caveat) : null))))))) : null,
    sourceList(mm.sources));
});
