/* ===================== Views: gap registry, gap detail ===================== */
const CATEGORY_NAMES = { A: 'A · Unsolved technical', B: 'B · Integration', C: 'C · Workflow', D: 'D · Deployment / DDIL', E: 'E · Procurement', F: 'F · Security / releasability', G: 'G · Usability', H: 'H · Economic', I: 'I · Data', J: 'J · No real opportunity' };
const CRITERIA = ['severity_of_user_pain', 'frequency_of_pain', 'budget_evidence', 'procurement_accessibility', 'technical_feasibility', 'feasibility_with_250k', 'time_to_credible_demo', 'availability_of_required_data', 'regulatory_accessibility', 'ability_to_start_unclassified', 'competitive_intensity', 'incumbent_vulnerability', 'integration_feasibility', 'potential_moat', 'dual_use_potential', 'expansion_potential', 'repeat_purchase_potential', 'founder_team_fit'];
const MARKET_SET = new Set([1, 2, 3, 4, 5, 11, 12, 13, 14, 15, 16, 17]);

route('gaps', (r) => {
  if (r.id) return gapDetail(r);
  const reg = arr(D.registry?.gaps);
  const rows = reg.map((g) => ({ ...g, score: D.gaps?.[g.id]?.score, card: D.gaps?.[g.id]?.card }));
  const cols = [
    { key: 'id', title: 'ID', render: (g) => h('span', { class: 'mono' }, g.id) },
    { key: 'title', title: 'Gap', render: (g) => h('div', null, h('a', { href: '#gaps/' + g.id }, h('b', null, g.title)), h('span', { class: 'cell-sub' }, g.problem)), width: '360px' },
    { key: 'categories', title: 'Categories', render: (g) => chips(g.categories, 'cat') },
    { key: 'segment_ids', title: 'Segments', render: (g) => h('div', { class: 'chips' }, arr(g.segment_ids).map((s) => h('a', { class: 'chip mono', href: '#segments/' + s }, s))) },
    { key: 'verdict', title: 'Verdict', render: (g) => verdictBadge(g.score?.verdict), sort: (g) => ({ survive: 0, borderline: 1, kill: 2 }[String(g.score?.verdict || '').toLowerCase()] ?? 3) },
    { key: 'market', title: 'Market', num: true, render: (g) => scorePill(g.score?.market_attractiveness ?? 0), sort: (g) => num(g.score?.market_attractiveness) },
    { key: 'fit', title: 'Founder fit', num: true, render: (g) => scorePill(g.score?.founder_fit ?? 0), sort: (g) => num(g.score?.founder_fit) },
    { key: 'evidence_forms', title: 'Evidence forms', num: true, render: (g) => String(g.card ? new Set(arr(g.card.evidence).map((e) => e.form)).size : g.evidence_forms ?? '—'), sort: (g) => (g.card ? new Set(arr(g.card.evidence).map((e) => e.form)).size : num(g.evidence_forms)) },
    { key: 'stage', title: 'Market stage', render: (g) => stageChip(g.card?.market_stage) || '—', sort: (g) => g.card?.market_stage || '' },
  ];
  const el = arr(D.founderfit?.elimination_log);
  return h('div', { class: 'page' },
    pageHead('Deliverables 6 & 7 · Gap registry', reg.length + ' candidate gaps, red-teamed and scored', 'Every candidate gap was consolidated from the segment analyses, given a full Gap Evidence Card with at least three forms of evidence where they exist, attacked by three independent skeptics (market and budget; incumbents and competition; feasibility, access and founder fit), then scored on 18 criteria. Weak gaps are killed explicitly rather than quietly dropped.'),
    h('div', { class: 'row' }, Object.entries(CATEGORY_NAMES).map(([k, v]) => chip(v, 'outline'))),
    dataTable(rows, cols, { facets: [{ title: 'Verdict', get: (g) => g.score?.verdict }, { title: 'Category', get: (g) => g.categories }, { title: 'Segment', get: (g) => g.segment_ids }], sortKey: 'verdict', id: 'gaps', pageSize: 50, placeholder: 'Filter gaps…' }),
    arr(D.registry?.dropped).length ? fold('Candidates dropped or merged during consolidation (' + arr(D.registry.dropped).length + ')', dataTable(arr(D.registry.dropped), [{ key: 'candidate_id', title: 'Candidate' }, { key: 'reason', title: 'Reason' }], { filterable: false })) : null,
    D.registry?.coverage_notes ? card('Coverage notes', h('p', null, D.registry.coverage_notes)) : null,
    el.length ? card('Elimination log', dataTable(el, [{ key: 'gap_id', title: 'Gap', render: (x) => h('a', { href: '#gaps/' + x.gap_id }, x.gap_id + ' ' + (x.title || '')) }, { key: 'verdict', title: 'Verdict', render: (x) => verdictBadge(x.verdict) }, { key: 'decisive_reason', title: 'Decisive reason' }, { key: 'narrower_version', title: 'Narrower surviving version' }], { filterable: false, pageSize: 50 })) : null);
});

function gapDetail(r) {
  const reg = arr(D.registry?.gaps).find((g) => g.id === r.id);
  const g = D.gaps?.[r.id] || {}; const c = g.card || {}; const s = g.score || {};
  if (!reg && !c.id) return h('div', { class: 'page' }, crumbs([{ text: 'Gap registry', href: '#gaps' }]), empty('Unknown gap.'));
  const title = c.title || reg?.title || r.id;
  const isSurvivor = arr(D.survivorsOrder).includes(r.id);
  const scores = arr(s.scores);
  const marketItems = scores.filter((x) => MARKET_SET.has(x.n)).map((x) => ({ label: titleCase(x.criterion), value: x.score, tip: esc(x.rationale || ''), warn: x.score <= 1 }));
  const fitItems = scores.filter((x) => !MARKET_SET.has(x.n)).map((x) => ({ label: titleCase(x.criterion), value: x.score, tip: esc(x.rationale || ''), warn: x.score <= 1 }));
  const rt = s.red_team || {};
  const lensCard = (key, name) => { const v = rt[key] || {}; return h('div', { class: 'lens' + (v.refuted ? ' refuted' : '') }, h('div', { class: 'row' }, h('b', null, name), v.refuted === true ? chip('Refuted', 'bad') : v.refuted === false ? chip('Not refuted', 'good') : chip('n/a', 'outline')), strengthMeter(v.strength), h('p', { class: 'small' }, v.summary || '—')); };
  const pending = !c.id;
  const registryView = () => h('div', { class: 'stack' },
    h('div', { class: 'callout amber' }, h('div', { class: 'eyebrow' }, 'Stage status'), h('p', null, 'Gap Evidence Card, three-lens red team and 18-criterion scores are pending for this gap. What follows is the consolidated registry entry: the problem statement, the evidence already gathered by the segment analyses, and the companies closest to the problem.')),
    h('div', { class: 'two-col' },
      card('Registry entry', kv([['Problem', reg?.problem], ['User', reg?.user], ['Initial attractiveness', reg?.initial_attractiveness ? chip(reg.initial_attractiveness, /high/i.test(reg.initial_attractiveness) ? 'good' : /med/i.test(reg.initial_attractiveness) ? 'warn' : 'outline') : '—'], ['Distinct evidence forms already found', reg?.evidence_forms], ['Consolidated from', h('div', { class: 'chips' }, arr(reg?.merged_from).map((m) => h('a', { class: 'chip mono', href: '#segments/' + m.split('-')[0] + '/candidate-gaps' }, m)))], ['Notes', reg?.notes]])),
      card('Companies near the problem', arr(reg?.companies_near).length ? h('div', { class: 'chips' }, arr(reg.companies_near).map((n) => { const cc = findCompany(n); return cc ? h('a', { class: 'chip accent', href: '#companies/' + cc.slug }, n) : chip(n); })) : empty('None recorded.'))),
    card('Key evidence pointers (' + arr(reg?.key_evidence_pointers).length + ')', arr(reg?.key_evidence_pointers).length ? evidenceList(arr(reg.key_evidence_pointers).map((e) => (isStr(e) ? e : { claim: e.note || e.claim || '', source_url: e.source_url || e.url, pub_date: e.pub_date }))) : empty()),
    arr(reg?.merged_from).length ? card('Source candidate gaps from the segment analyses', h('div', { class: 'stack' }, arr(reg.merged_from).map((m) => { const seg = arr(D.segments).find((x) => x.segment_id === m.split('-')[0]); const cg = arr(seg?.candidate_gaps).find((x) => x.id === m); return cg ? fold(h('span', null, h('span', { class: 'mono muted' }, m + ' '), cg.title), h('div', { class: 'stack' }, kv([['Problem', cg.problem_one_sentence], ['User', cg.user], ['Current workflow', cg.current_workflow], ['Current solution', cg.current_solution], ['Failure point', cg.failure_point], ['Why startups haven\'t solved it', cg.why_startups_havent_solved], ['Incumbent response risk', cg.incumbent_response_risk], ['Technical wedge (hypothesis)', cg.technical_wedge_hypothesis], ['MVP sketch', cg.mvp_sketch], ['Entry vehicle', cg.entry_vehicle], ['Why now', cg.why_now], ['Killer risk', cg.killer_risk]]), h('h4', null, 'Evidence'), evidenceList(cg.evidence))) : null; }))) : null);
  const tabDefs = pending ? [{ title: 'Registry entry', render: registryView }] : [
    { title: 'Evidence card', render: () => h('div', { class: 'stack' },
      h('div', { class: 'two-col' },
        card('The problem', kv([['Problem', c.problem || reg?.problem], ['User', c.user ? [c.user.exact_role, c.user.echelon].filter(Boolean).join(' · ') + (arr(c.user.organization_examples).length ? ' (' + arr(c.user.organization_examples).join(', ') + ')' : '') : reg?.user], ['Chain steps', val(c.chain_steps, { chips: true })], ['Echelons', val(c.echelons, { chips: true })], ['Current solution', c.current_solution], ['Failure', c.failure]])),
        card('Current workflow', arr(c.current_workflow).length ? h('ol', null, arr(c.current_workflow).map((w) => h('li', null, isStr(w) ? w : val(w)))) : empty())),
      card('Evidence (' + arr(c.evidence).length + ' items · ' + new Set(arr(c.evidence).map((e) => e.form)).size + ' distinct forms)', h('p', { class: 'small muted' }, 'A claimed gap needs at least three different forms of evidence: government document, operator workaround, RFI or sources sought, budget, product failing a requirement, multiple partial solutions without scale, repeated procurement, documented manual workaround.'), evidenceList(c.evidence)),
      h('div', { class: 'two-col' },
        card('Why existing startups haven\'t solved it', h('p', null, c.why_existing_startups_havent_solved || '—'), arr(c.why_not_solved_reasons).length ? h('div', { class: 'chips', style: { marginTop: '8px' } }, arr(c.why_not_solved_reasons).map((x) => chip(x, 'outline'))) : null),
        card('Why now', h('p', null, c.why_now || '—'))),
      h('div', { class: 'two-col' },
        card('Technical wedge', h('p', null, c.technical_wedge || '—'), h('h4', { style: { margin: '10px 0 4px' } }, 'MVP'), kv([['What', c.mvp?.what], ['Demonstrable in 3–6 months', c.mvp?.demonstrable_in_3_6_months], ['Must prove', c.mvp?.what_it_must_prove], ['Uses', val(c.mvp?.uses, { chips: true })]])),
        card('Data and integration', kv([['Data needed', c.data_requirement?.what], ['Obtainable?', c.data_requirement?.legally_realistically_obtainable], ['Data sources', val(c.data_requirement?.sources, { chips: true })], ['Systems to integrate', val(c.integration_requirement?.systems, { chips: true })], ['Interfaces / protocols', val(c.integration_requirement?.interfaces_protocols, { chips: true })], ['Who controls the interface', c.integration_requirement?.who_controls_the_interface]]))),
      h('div', { class: 'two-col' },
        card('Customer and budget', kv([['User', c.customer?.user], ['Champion', c.customer?.champion], ['Signs the contract', c.customer?.contract_signer], ['Requirement owner', c.customer?.requirement_owner], ['Program office', c.customer?.program_office], ['Contracting office', c.customer?.contracting_office], ['Budget', c.budget ? h('div', null, c.budget.program_or_line || '—', c.budget.evidence ? h('div', { class: 'small' }, c.budget.evidence) : null, c.budget.source_url ? h('a', { class: 'small', href: c.budget.source_url, target: '_blank', rel: 'noopener' }, shortUrl(c.budget.source_url)) : null, confTag(c.budget.confidence)) : '—'], ['Entry vehicle', c.entry_vehicle ? h('div', null, h('b', null, c.entry_vehicle.primary || '—'), arr(c.entry_vehicle.sequence).length ? h('ol', { class: 'small' }, arr(c.entry_vehicle.sequence).map((x) => h('li', null, isStr(x) ? x : val(x)))) : null, c.entry_vehicle.eligibility_notes ? h('div', { class: 'small muted' }, c.entry_vehicle.eligibility_notes) : null) : '—']])),
        card('Competition and incumbent response', arr(c.competition).length ? h('div', { class: 'table-wrap' }, h('table', { class: 'data' }, h('thead', null, h('tr', null, h('th', null, 'Company'), h('th', null, 'How close'), h('th', null, 'Evidence'))), h('tbody', null, arr(c.competition).map((x) => h('tr', null, h('td', null, companyLink(x.company)), h('td', null, x.how_close || '—'), h('td', { class: 'small' }, x.evidence || '—')))))) : empty(), h('div', { class: 'callout bear', style: { marginTop: '10px' } }, h('div', { class: 'eyebrow' }, 'Could Anduril / Palantir / L3Harris add it?'), h('p', null, c.incumbent_response?.could_anduril_palantir_l3harris_add_it || '—'), h('p', { style: { marginTop: '6px' } }, h('b', null, 'Why a startup still wins, or reject: '), c.incumbent_response?.why_startup_still_wins_or_reject || '—')))),
      h('div', { class: 'grid cols-3' },
        card('Capital required', kv([['Proof of concept', c.capital_required?.proof_of_concept_usd], ['Credible military demo', c.capital_required?.credible_military_demo_usd], ['First production deployment', c.capital_required?.first_production_deployment_usd], ['Assumptions', c.capital_required?.assumptions]])),
        card('Expertise required', arr(c.expertise_required).length ? h('ul', null, arr(c.expertise_required).map((x) => h('li', null, h('b', null, x.role), x.fatal_if_absent ? chip('fatal if absent', 'bad') : null, x.why ? h('div', { class: 'small muted' }, x.why) : null))) : empty()),
        card('Regulatory and classification', kv([['Regulatory burden', c.regulatory_burden ? h('div', null, chip(c.regulatory_burden.level || '—', /high/i.test(c.regulatory_burden.level) ? 'bad' : /med/i.test(c.regulatory_burden.level) ? 'warn' : 'good'), h('div', { class: 'small' }, c.regulatory_burden.explanation), c.regulatory_burden.non_us_person_founder_note ? h('div', { class: 'small muted' }, 'Non-U.S.-person founder: ' + c.regulatory_burden.non_us_person_founder_note) : null) : '—'], ['Classification dependence', c.classification_dependence], ['Dual-use potential', c.dual_use_potential ? h('div', null, chip(c.dual_use_potential.level || '—', 'outline'), h('div', { class: 'small' }, c.dual_use_potential.explanation)) : '—'], ['Defensibility', c.defensibility ? h('div', null, chips(c.defensibility.what_becomes_proprietary, 'accent'), h('div', { class: 'small' }, c.defensibility.explanation)) : '—']]))),
      h('div', { class: 'two-col' }, card(h('div', { class: 'card-head' }, h('h3', null, 'Market stage'), stageChip(c.market_stage)), timeline(c.procurement_signal_timeline)), card('Allied extension', h('p', null, c.allied_extension || '—'))),
      h('div', { class: 'callout bear' }, h('div', { class: 'eyebrow' }, 'Killer risk'), h('p', null, c.killer_risk || '—')),
      sourceList(c.sources)) },
    { title: 'Red team', render: () => h('div', { class: 'stack' },
      h('p', { class: 'lede' }, 'Three independent skeptics were told to write the strongest possible bear case and to default to "refuted" when uncertain. Strength 5 means the bear case is close to decisive.'),
      h('div', { class: 'grid cols-3' }, lensCard('market', 'Market / budget skeptic'), lensCard('competition', 'Incumbent / competition skeptic'), lensCard('feasibility', 'Feasibility / access / founder-fit skeptic')),
      arr(g.verdicts).length ? card('Skeptic detail', h('div', { class: 'stack' }, arr(g.verdicts).map((v) => fold(h('span', null, h('b', null, titleCase(v.lens)), ' ', v.refuted ? chip('refuted', 'bad') : chip('not refuted', 'good'), ' ', strengthMeter(v.strength)), h('div', { class: 'stack' }, h('div', { class: 'callout bear' }, h('div', { class: 'eyebrow' }, 'Strongest single argument'), h('p', null, v.strongest_single_argument || '—')), h('div', { class: 'prose' }, h('p', null, v.bear_case || '—')), arr(v.evidence).length ? h('div', null, h('h4', null, 'Evidence'), evidenceList(v.evidence)) : null, v.what_would_change_my_mind ? kv([['What would change my mind', v.what_would_change_my_mind], ['Narrower survivable version', v.narrower_survivable_version]]) : null))))) : null,
      h('div', { class: 'two-col' }, h('div', { class: 'callout bull' }, h('div', { class: 'eyebrow' }, 'Bull case summary'), h('p', null, s.bull_case_summary || '—')), h('div', { class: 'callout bear' }, h('div', { class: 'eyebrow' }, 'Bear case summary'), h('p', null, s.bear_case_summary || '—')))) },
    { title: 'Scores & verdict', render: () => h('div', { class: 'stack' },
      h('div', { class: 'row' }, verdictBadge(s.verdict), h('span', null, 'Market attractiveness ', scorePill(s.market_attractiveness ?? 0)), h('span', null, 'Founder fit ', scorePill(s.founder_fit ?? 0)), confTag(s.confidence)),
      s.verdict_rationale ? h('div', { class: 'callout' }, h('div', { class: 'eyebrow' }, 'Verdict rationale'), h('p', null, s.verdict_rationale)) : null,
      s.narrower_version_if_borderline ? h('div', { class: 'callout amber' }, h('div', { class: 'eyebrow' }, 'Narrower version that survives'), h('p', null, s.narrower_version_if_borderline)) : null,
      h('div', { class: 'two-col' }, card('Market attractiveness (independent of this team)', h('p', { class: 'small muted' }, 'Hover a bar for the rationale. Amber marks scores of 0 or 1.'), scores.length ? scoreBars(marketItems) : empty()), card('Founder fit (two founders, ~$250k)', scores.length ? scoreBars(fitItems) : empty())),
      scores.length ? fold('All 18 scores with rationale', h('div', { class: 'table-wrap' }, h('table', { class: 'data' }, h('thead', null, h('tr', null, h('th', null, '#'), h('th', null, 'Criterion'), h('th', { class: 'num' }, 'Score'), h('th', null, 'Rationale'))), h('tbody', null, scores.map((x) => h('tr', null, h('td', { class: 'mono' }, String(x.n)), h('td', null, titleCase(x.criterion)), h('td', { class: 'num' }, scorePill(x.score)), h('td', { class: 'small' }, x.rationale || '—'))))))) : null,
      s.most_important_question_answer ? card('The most important question', h('p', { class: 'small muted' }, 'If two exceptionally capable founders had $250,000 today: what would they build first, who would they show it to, what would it prove, why would the customer care, why can\'t an incumbent trivially crush them, and what milestone justifies the next $2–5M?'), h('div', { class: 'prose' }, h('p', null, s.most_important_question_answer))) : null) },
  ];
  return h('div', { class: 'page' }, crumbs([{ text: 'Gap registry', href: '#gaps' }, { text: r.id }]), pageHead(r.id + ' · Gap Evidence Card', title, c.problem || reg?.problem, [verdictBadge(s.verdict), ...arr(c.categories || reg?.categories).map((k) => chip(CATEGORY_NAMES[k] || k, 'cat')), ...arr(c.segment_ids || reg?.segment_ids).map((sid) => h('a', { class: 'chip mono', href: '#segments/' + sid }, sid)), isSurvivor ? h('a', { class: 'btn primary small', href: '#opportunities/' + r.id }, 'Open opportunity deep dive →') : null]), tabs(tabDefs, tabIndexFor(tabDefs, r.sub)));
}
