/* ===================== Views: method, mandate, boot ===================== */
route('method', () => {
  const cr = D.critic || {};
  const m = D.meta || {};
  const seg = arr(D.segments);
  return h('div', { class: 'page' },
    pageHead('Method', 'How this map was built, and how much to trust it', 'Forty-plus research agents swept government primary sources first, then company sources, then independent reporting and financial databases. Every gap was red-teamed by three independent skeptics before scoring. The audit below records what the completeness critic found.'),
    card('Research rules applied', h('ol', null, ['Current claims must be sourced; publication date and event/award date are recorded where they differ.', 'Government primary sources are preferred for government programs; contract databases over company claims for award verification.', 'A startup\'s marketing claim is never cited as independent proof its product works.', 'Every substantive claim is labeled FACT, INFERENCE or HYPOTHESIS, with HIGH / MEDIUM / LOW confidence on uncertain conclusions.', 'Where public information ends, the record says "Public evidence insufficient." No classified architecture is speculated.', 'Absence of competitors is not evidence of opportunity; no gap is recommended without explaining why existing vendors do not solve it.', 'IDIQ ceiling is never treated as revenue; prototype award is never treated as scaled deployment; selected vendor is never treated as production program.', 'No definitive immigration, ITAR, EAR, FOCI or clearance legal judgments are made; the constraints are described and flagged for counsel.'].map((x) => h('li', null, x)))),
    card('Pipeline', h('ol', null, ['Phase 1–2: first-principles chain map and 14 segment deep dives (one agent each, 25–40 searches per segment).', 'Phase 3–4: buyer maps for Joint/OSD, Army, Air Force, Navy & Marine Corps, Space Force.', 'Phase 5–6: company database in batches of seven, plus two discovery agents mining SBIR, xTech, AFWERX, DIU, program vendor rosters and venture portfolios.', 'Evidence sweeps: GAO and DoD IG; SAM.gov RFIs and sources sought; exercises; SBIR and prototype patterns; budget lines; allied markets; regulatory and eligibility constraints.', 'Phase 8: gap registry consolidation, then a Gap Evidence Card per gap with fresh web verification.', 'Phase 10: three independent skeptics per gap (market/budget; incumbents/competition; feasibility/access/founder fit), each instructed to default to "refuted" when uncertain.', 'Phase 9: 18-criterion scoring with every 0, 1 or 5 explained; market attractiveness and founder fit computed separately; verdict survive / borderline / kill.', 'Phases 11–12, 19–21: for survivors, technical architecture, MVP under $100k, capital map by stage, expertise map, money map, procurement-signal timeline, customer discovery plan, 90-day plan with kill criteria.', 'Syntheses: executive landscape, white-space test, money map, founder fit and opportunity matrix, and a completeness critic that audited the corpus.'].map((x) => h('li', null, x)))),
    cr.overall_assessment ? card('Completeness critic', h('div', { class: 'callout' }, h('p', null, cr.overall_assessment)), h('div', { class: 'grid cols-2', style: { marginTop: '12px' } }, arr(cr.recommended_fixes).length ? h('div', null, h('h4', null, 'Recommended fixes'), h('ul', { class: 'small' }, arr(cr.recommended_fixes).map((x) => h('li', null, chip(x.priority || '—', /high/i.test(x.priority) ? 'bad' : /med/i.test(x.priority) ? 'warn' : 'outline'), ' ', h('span', { class: 'mono' }, x.file), ': ', x.fix)))) : null, arr(cr.fixes_applied).length ? h('div', null, h('h4', null, 'Fixes applied'), h('ul', { class: 'small' }, arr(cr.fixes_applied).map((x) => h('li', null, h('span', { class: 'mono' }, x.file), ': ', x.fix)))) : null), arr(cr.contract_violations).length ? fold('Contract-data violations found (' + arr(cr.contract_violations).length + ')', val(cr.contract_violations)) : null, arr(cr.contradictions).length ? fold('Contradictions between files (' + arr(cr.contradictions).length + ')', val(cr.contradictions)) : null, arr(cr.naming_issues).length ? fold('Organization naming issues (' + arr(cr.naming_issues).length + ')', val(cr.naming_issues)) : null, arr(cr.speculation_flags).length ? fold('Speculation flags (' + arr(cr.speculation_flags).length + ')', val(cr.speculation_flags)) : null, arr(cr.unsourced_claims).length ? fold('Unsourced claims sampled (' + arr(cr.unsourced_claims).length + ')', val(cr.unsourced_claims)) : null, arr(cr.unconvincing_miq).length ? fold('Survivors whose "most important question" answer the critic found unconvincing', val(cr.unconvincing_miq)) : null, cr.counts ? h('p', { class: 'small muted' }, 'Counts audited: ' + JSON.stringify(cr.counts)) : null) : null,
    card('Saturation statements by segment', h('div', { class: 'stack' }, seg.map((s) => fold(s.segment_id + ' ' + s.segment_name, h('p', { class: 'small' }, s.saturation_statement || '—'))))),
    m.counts ? card('Corpus statistics', kv(Object.entries(m.counts).map(([k, v]) => [titleCase(k), String(v)]))) : null,
    h('p', { class: 'small muted' }, 'Generated ' + (m.generated || '') + '. This page is a single local HTML file; all data is embedded. Open it from disk without a server.'));
});

route('mandate', () => h('div', { class: 'page' }, pageHead('Research mandate', 'The brief this map answers', 'The founders\' original deep-research mandate, kept verbatim so every deliverable can be checked against what was asked.'), h('div', { class: 'card' }, h('pre', { style: { whiteSpace: 'pre-wrap', fontFamily: 'var(--font-body)', fontSize: '14px', margin: 0, maxWidth: '80ch' } }, D.mandate || ''))));

/* ---------- Boot ---------- */
function boot() { initTheme(); buildSidebar(); initSearch(); navigate(); }
if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot); else boot();
