/* ===================== Views: surviving opportunities, plans, founder fit, whitespace ===================== */
const CAPITAL_KEYS = ['salaries', 'compute', 'sensors', 'rf_equipment', 'prototype_hardware', 'manufacturing', 'testing', 'travel', 'compliance', 'legal', 'security', 'insurance', 'cloud', 'subcontract_engineering'];
const CAPITAL_GROUPS = { salaries: 'salaries', compute: 'compute_cloud', cloud: 'compute_cloud', sensors: 'hardware', rf_equipment: 'hardware', prototype_hardware: 'hardware', manufacturing: 'hardware', testing: 'testing_travel', travel: 'testing_travel', compliance: 'compliance_legal_security', legal: 'compliance_legal_security', security: 'compliance_legal_security', insurance: 'compliance_legal_security', subcontract_engineering: 'subcontract_engineering' };
const CAPITAL_GROUP_ORDER = ['salaries', 'compute_cloud', 'hardware', 'testing_travel', 'compliance_legal_security', 'subcontract_engineering', 'other'];

route('opportunities', (r) => {
  if (r.id) return opportunityDetail(r);
  const order = arr(D.survivorsOrder);
  const rows = order.map((id) => ({ id, reg: (D.registry?.gaps || []).find((g) => g.id === id) || {}, score: D.gaps?.[id]?.score || {}, card: D.gaps?.[id]?.card || {}, tech: D.survivors?.[id]?.tech, gtm: D.survivors?.[id]?.gtm }));
  return h('div', { class: 'page' },
    pageHead('Deliverable 7 · Surviving opportunities', rows.length ? (rows.filter((x) => /surv|border/i.test(x.score.verdict)).length + ' of ' + arr(D.registry?.gaps).length + ' gaps survived the red team; ' + rows.length + ' deep dives') : 'Survivors are decided by the red team and scoring stage', 'Each survivor carries a full technical architecture, an MVP that two founders can demonstrate for under $100k, a capital map by stage, an expertise map with the first five hires, a money map, a procurement-signal timeline, a customer-discovery plan, and a 90-day validation plan with explicit kill criteria.'),
    rows.length ? h('div', { class: 'callout amber' }, h('p', null, 'The red team killed 35 of 36 gaps and left one borderline. Deep dives were run for the borderline survivor and for the two highest-scoring killed paths so that the founders have three complete, testable 90-day plans; each killed path is labelled as such, and its plan\'s kill criteria are designed to confirm or refute the verdict.')) : pendingCandidates(),
    rows.length ? h('div', { class: 'grid cols-2' }, rows.map((x) => h('a', { class: 'seg-card', href: '#opportunities/' + x.id }, h('div', { class: 'row' }, h('span', { class: 'seg-id' }, x.id), verdictBadge(x.score.verdict), stageChip(x.card.market_stage)), h('h3', null, x.reg.title || x.id), D.survivors?.[x.id]?.status ? h('div', { class: 'small' }, chip(D.survivors[x.id].status, /surv|border/i.test(D.survivors[x.id].status) ? 'good' : 'warn')) : null, h('div', { class: 'seg-sum' }, x.card.problem || x.reg.problem || ''), h('div', { class: 'row' }, h('span', { class: 'small muted' }, 'Market '), scorePill(x.score.market_attractiveness ?? 0), h('span', { class: 'small muted' }, 'Founder fit '), scorePill(x.score.founder_fit ?? 0), chips(x.reg.categories, 'cat')), x.tech?.mvp?.total_cost_usd ? h('div', { class: 'small muted' }, 'MVP ' + fmtMoney(x.tech.mvp.total_cost_usd) + (x.tech.capital_map?.next_milestone ? ' → ' + x.tech.capital_map.next_milestone.slice(0, 90) : '')) : null))) : empty('No survivors recorded yet.'),
    D.founderfit?.opportunity_matrix ? card('Opportunity matrix', h('p', { class: 'small muted' }, 'Rows are surviving opportunities; cells carry a 0–5 rating (darker is better) and a short phrase. Hover for the phrase.'), opportunityMatrix(D.founderfit.opportunity_matrix)) : null);
});

function pendingCandidates() {
  const reg = arr(D.registry?.gaps).filter((g) => !/^low/i.test(String(g.initial_attractiveness || '')));
  if (!reg.length) return empty('No survivors recorded yet.');
  return h('div', { class: 'stack' }, h('div', { class: 'callout amber' }, h('p', null, 'Stage status: the ' + reg.length + ' high- and medium-rated registry gaps below are the candidates entering the three-lens red team and 18-criterion scoring. Survivors then receive the full deep dive (architecture, MVP under $100k, capital map, expertise map, money map, customer discovery and 90-day plan).')), h('div', { class: 'grid cols-2' }, reg.map((g) => h('a', { class: 'seg-card', href: '#gaps/' + g.id }, h('div', { class: 'row' }, h('span', { class: 'seg-id' }, g.id), chip(g.initial_attractiveness || '—', /high/i.test(g.initial_attractiveness) ? 'good' : 'warn'), chips(g.segment_ids, 'mono')), h('h3', null, g.title), h('div', { class: 'seg-sum' }, g.problem || ''), chips(g.categories, 'cat')))));
}
function opportunityMatrix(m) {
  const cols = arr(m.columns); const rows = arr(m.rows);
  if (!rows.length) return empty();
  const grid = h('div', { class: 'heat', style: { gridTemplateColumns: 'minmax(180px, auto) repeat(' + cols.length + ', minmax(72px, 1fr)) 70px 70px' } });
  grid.append(h('div'));
  cols.forEach((c) => grid.append(h('div', { class: 'hx' }, titleCase(c))));
  grid.append(h('div', { class: 'hx' }, 'Market'), h('div', { class: 'hx' }, 'Fit'));
  rows.forEach((row) => {
    grid.append(h('a', { class: 'hy', href: '#opportunities/' + row.gap_id, style: { textAlign: 'left', whiteSpace: 'normal' } }, row.gap_id + ' ' + (row.title || '')));
    cols.forEach((c) => { const cell = (row.cells || {})[c] || {}; const v = clamp(Math.round(num(cell.score)), 0, 5); const el = h('div', { class: 'cell', style: { background: v ? `var(--seq-${v + 1})` : 'var(--surface-2)', color: v >= 3 ? '#fff' : 'var(--ink)' } }, String(v)); withTip(el, `<b>${esc(titleCase(c))}</b><br>${esc(cell.text || '')}`); grid.append(el); });
    grid.append(h('div', { class: 'cell', style: { background: 'var(--surface-2)' } }, scorePill(row.market_attractiveness ?? 0)), h('div', { class: 'cell', style: { background: 'var(--surface-2)' } }, scorePill(row.founder_fit_score ?? 0)));
  });
  return h('div', { class: 'stack' }, h('div', { style: { overflowX: 'auto' } }, grid), fold('Table view', h('div', { class: 'table-wrap' }, h('table', { class: 'data' }, h('thead', null, h('tr', null, h('th', null, 'Opportunity'), cols.map((c) => h('th', null, titleCase(c))))), h('tbody', null, rows.map((row) => h('tr', null, h('td', null, row.gap_id + ' ' + (row.title || '')), cols.map((c) => h('td', { class: 'small' }, ((row.cells || {})[c] || {}).score + ' · ' + (((row.cells || {})[c] || {}).text || ''))))))))));
}

function opportunityDetail(r) {
  const id = r.id; const reg = arr(D.registry?.gaps).find((g) => g.id === id) || {}; const g = D.gaps?.[id] || {}; const c = g.card || {}; const s = g.score || {};
  const t = D.survivors?.[id]?.tech || {}; const m = D.survivors?.[id]?.gtm || {};
  if (!t.id && !m.id) return h('div', { class: 'page' }, crumbs([{ text: 'Opportunities', href: '#opportunities' }]), empty('No deep dive recorded for ' + id + '.'), h('p', null, h('a', { href: '#gaps/' + id }, 'Open the gap card →')));
  const a = t.architecture || {};
  const graph = arr(a.graph?.nodes).length ? layeredGraph(arr(a.graph.nodes), arr(a.graph.edges), { layers: ['input', 'compute', 'core', 'interface', 'output', 'user'], layerOf: (n) => n.kind, nodeW: 150, nodeH: 54, gapX: 56, label: 'Technical architecture' }) : empty();
  const stages = arr(t.capital_map?.stages);
  const capRows = stages.map((st) => { const segs = {}; for (const li of arr(st.line_items)) { const k = CAPITAL_GROUPS[li.item] || 'other'; segs[k] = (segs[k] || 0) + (num(li.usd_high) || num(li.usd_low)); } return { label: 'Stage ' + st.stage + ' · ' + (st.name || ''), segments: CAPITAL_GROUP_ORDER.filter((k) => segs[k]).map((k) => ({ key: k, value: segs[k] })), total: num(st.total_usd_high) || Object.values(segs).reduce((x, y) => x + y, 0) }; });
  const miq = m.most_important_question || {};
  const plan = m.plan_90_days || {};
  const PHASES = [['weeks_1_3', 'Weeks 1–3 · Research & customer interviews'], ['weeks_4_6', 'Weeks 4–6 · Technical experiments'], ['weeks_7_9', 'Weeks 7–9 · Prototype'], ['weeks_10_12', 'Weeks 10–12 · User validation & demo']];
  const LINKS = ['problem', 'user', 'requirement_owner', 'program_office', 'contracting_office', 'budget', 'contract_vehicle', 'current_vendors'];
  const tabDefs = [
    { title: 'Thesis', render: () => h('div', { class: 'stack' },
      card('The most important question', h('p', { class: 'small muted' }, 'If two exceptionally capable founders had $250,000 today…'), kv([['What to build first', miq.build_first], ['Who to show it to', miq.show_it_to], ['What the demo proves', miq.demo_proves], ['Why the customer cares', miq.why_customer_cares], ['Why an incumbent can\'t trivially crush them', miq.why_incumbent_cant_crush], ['Milestone that justifies the next $2–5M', miq.milestone_for_next_2_5m]])),
      t.version_designed_for ? h('div', { class: 'callout amber' }, h('div', { class: 'eyebrow' }, 'Version designed for'), h('p', null, t.version_designed_for)) : null,
      h('div', { class: 'two-col' }, h('div', { class: 'callout bull' }, h('div', { class: 'eyebrow' }, 'Bull case'), h('p', null, s.bull_case_summary || c.technical_wedge || '—')), h('div', { class: 'callout bear' }, h('div', { class: 'eyebrow' }, 'Bear case'), h('p', null, s.bear_case_summary || c.killer_risk || '—'))),
      h('p', { class: 'small' }, h('a', { href: '#gaps/' + id }, 'Open the full Gap Evidence Card, red team and scores →'))) },
    { title: 'Architecture & MVP', render: () => h('div', { class: 'stack' },
      card('Technical architecture', h('p', null, a.prose || '—'), graph),
      h('div', { class: 'two-col' }, card('Engineering', kv([['Hardest problem', a.hardest_problem], ['Commodity', val(a.commodity, { chips: true })], ['Must be proprietary', val(a.must_be_proprietary, { chips: true })], ['Dependencies', val(a.dependencies, { chips: true })], ['Third-party hardware', val(a.third_party_hardware, { chips: true })], ['Integration burden', a.integration_burden]])), card('Open source and metrics', arr(a.open_source).length ? h('div', { class: 'table-wrap' }, h('table', { class: 'data' }, h('thead', null, h('tr', null, h('th', null, 'Project'), h('th', null, 'License'), h('th', null, 'Use'))), h('tbody', null, arr(a.open_source).map((o) => h('tr', null, h('td', null, o.project), h('td', { class: 'mono' }, o.license || '—'), h('td', null, o.use || '—')))))) : empty(), h('h4', { style: { margin: '12px 0 6px' } }, 'Performance metrics customers care about'), arr(a.performance_metrics).length ? h('ul', { class: 'small' }, arr(a.performance_metrics).map((p) => h('li', null, h('b', null, p.metric), ': ', p.target, p.why ? h('span', { class: 'muted' }, ' — ' + p.why) : null))) : empty())),
      card(h('div', { class: 'card-head' }, h('h3', null, 'MVP for two founders'), t.mvp?.total_cost_usd ? chip('Total ' + fmtMoney(t.mvp.total_cost_usd), 'amber') : null), kv([['Demo', t.mvp?.demo], ['Must prove', val(t.mvp?.must_prove)], ['Uses', val(t.mvp?.uses, { chips: true })], ['Kill criteria', val(t.mvp?.kill_criteria)]]), h('div', { class: 'two-col', style: { marginTop: '12px' } }, h('div', null, h('h4', null, 'Bill of materials'), arr(t.mvp?.bom).length ? h('div', { class: 'table-wrap' }, h('table', { class: 'data' }, h('thead', null, h('tr', null, h('th', null, 'Item'), h('th', { class: 'num' }, 'Cost'), h('th', null, 'Note'))), h('tbody', null, arr(t.mvp.bom).map((b) => h('tr', null, h('td', null, b.item), h('td', { class: 'num' }, fmtMoney(num(b.cost_usd))), h('td', { class: 'small' }, b.note || '—')))))) : empty()), h('div', null, h('h4', null, 'Build plan'), arr(t.mvp?.build_plan).length ? h('ol', null, arr(t.mvp.build_plan).map((b) => h('li', null, h('b', null, 'Month ' + b.month + ': '), b.work))) : empty()))),
      arr(t.engineering_risks).length ? card('Engineering risks', h('div', { class: 'table-wrap' }, h('table', { class: 'data' }, h('thead', null, h('tr', null, h('th', null, 'Risk'), h('th', null, 'Mitigation'))), h('tbody', null, arr(t.engineering_risks).map((x) => h('tr', null, h('td', null, x.risk), h('td', null, x.mitigation || '—'))))))) : null,
      sourceList(t.sources)) },
    { title: 'Capital & team', render: () => h('div', { class: 'stack' },
      card('Capital map by stage', h('p', { class: 'small muted' }, 'Bars use the high end of each line-item range; hover a segment for the amount. Stage totals are shown at right.'), capRows.length ? stackedBars(capRows, CAPITAL_GROUP_ORDER) : empty(), h('div', { class: 'callout', style: { marginTop: '12px' } }, h('div', { class: 'eyebrow' }, 'Does $250k reach the next fundable milestone?'), h('p', null, t.capital_map?.does_250k_reach_next_fundable_milestone || '—'), t.capital_map?.next_milestone ? h('p', { style: { marginTop: '6px' } }, h('b', null, 'Next milestone: '), t.capital_map.next_milestone) : null), stages.length ? fold('Stage detail and line items', h('div', { class: 'stack' }, stages.map((st) => h('div', null, h('h4', null, 'Stage ' + st.stage + ' · ' + (st.name || '') + (st.duration_months ? ' · ' + st.duration_months + ' months' : '') + ' · ' + fmtMoney(num(st.total_usd_low)) + '–' + fmtMoney(num(st.total_usd_high))), h('p', { class: 'small' }, h('b', null, 'Milestone: '), st.milestone || '—', ' ', h('b', null, 'Evidence produced: '), st.evidence_produced || '—'), h('div', { class: 'table-wrap' }, h('table', { class: 'data' }, h('thead', null, h('tr', null, h('th', null, 'Line item'), h('th', { class: 'num' }, 'Low'), h('th', { class: 'num' }, 'High'), h('th', null, 'Assumption'))), h('tbody', null, arr(st.line_items).map((li) => h('tr', null, h('td', null, titleCase(li.item)), h('td', { class: 'num' }, fmtMoney(num(li.usd_low))), h('td', { class: 'num' }, fmtMoney(num(li.usd_high))), h('td', { class: 'small' }, li.assumption || '—')))))))))) : null, t.capital_map?.assumptions ? h('p', { class: 'small muted' }, 'Assumptions: ' + t.capital_map.assumptions) : null),
      h('div', { class: 'two-col' }, card('First five hires after the founders', arr(t.expertise?.first_five_hires).length ? h('ol', null, arr(t.expertise.first_five_hires).map((x) => h('li', null, h('b', null, x.role), x.when ? h('span', { class: 'muted' }, ' · ' + x.when) : null, x.cost_range_usd ? h('span', { class: 'muted' }, ' · ' + x.cost_range_usd) : null, h('div', { class: 'small' }, x.why || '')))) : empty()), card('Fatal if absent', val(t.expertise?.fatal_if_absent))),
      card('Expertise matrix', expertiseMatrix(t.expertise?.matrix))) },
    { title: 'Go-to-market', render: () => h('div', { class: 'stack' },
      card('Money map', h('div', { class: 'money-chain' }, LINKS.map((k) => { const l = arr(m.money_map?.links).find((x) => x.link === k) || {}; return h('div', { class: 'money-link conf-' + String(l.confidence || '').toUpperCase() }, h('div', { class: 'ml-key' }, titleCase(k)), h('div', { class: 'ml-val' }, l.value || '—'), l.detail ? h('div', { class: 'ml-det' }, l.detail) : null, l.source_url ? h('a', { class: 'small', href: l.source_url, target: '_blank', rel: 'noopener' }, shortUrl(l.source_url)) : null); })), m.money_map?.weakest_link ? h('p', { class: 'small', style: { marginTop: '8px' } }, h('b', null, 'Weakest link: '), m.money_map.weakest_link, m.money_map.penalty_note ? ' · ' + m.money_map.penalty_note : '') : null),
      h('div', { class: 'two-col' }, card(h('div', { class: 'card-head' }, h('h3', null, 'Procurement signal'), stageChip(m.procurement_signal?.stage)), h('p', { class: 'small' }, m.procurement_signal?.rationale || ''), timeline(m.procurement_signal?.timeline)), card('Entry sequence', arr(m.entry_sequence).length ? h('ol', null, arr(m.entry_sequence).map((x) => h('li', null, h('b', null, x.vehicle), x.office_or_event ? ' — ' + x.office_or_event : '', x.timing ? h('span', { class: 'muted' }, ' · ' + x.timing) : null, x.what_it_yields ? h('div', { class: 'small' }, 'Yields: ' + x.what_it_yields) : null, x.eligibility_notes ? h('div', { class: 'small muted' }, 'Eligibility: ' + x.eligibility_notes) : null))) : empty())),
      h('div', { class: 'two-col' }, card('First deployment path', kv([['Path', m.first_deployment_path?.path], ['Evidence it produces', m.first_deployment_path?.evidence_it_produces], ['Alternatives', val(m.first_deployment_path?.alternatives)]])), card('Allied extension', kv([['Bigger with allies?', m.allied_extension?.bigger_with_allies], ['What changes', m.allied_extension?.what_changes], ['Markets', val(m.allied_extension?.markets, { chips: true })]]))),
      card('Customer discovery', h('div', { class: 'two-col' }, h('div', null, h('h4', null, 'Interview targets (roles, not names)'), arr(m.customer_discovery?.targets).length ? h('ul', null, arr(m.customer_discovery.targets).map((x) => h('li', null, h('b', null, x.role), x.why ? h('div', { class: 'small' }, x.why) : null, x.where_to_find ? h('div', { class: 'small muted' }, 'Where: ' + x.where_to_find) : null))) : empty()), h('div', null, h('h4', null, 'Workflow-discovery questions'), arr(m.customer_discovery?.questions).length ? h('ol', null, arr(m.customer_discovery.questions).map((q) => h('li', null, isStr(q) ? q : val(q)))) : empty()))),
      sourceList(m.sources)) },
    { title: '90-day plan', render: () => h('div', { class: 'stack' }, h('div', { class: 'row' }, plan.total_budget_usd ? chip('Total budget ' + fmtMoney(num(plan.total_budget_usd)), 'amber') : null), h('div', { class: 'plan' }, PHASES.map(([k, label]) => { const p = plan[k] || {}; return h('div', { class: 'phase' }, h('h4', null, label), p.owner ? h('div', { class: 'small muted' }, 'Owner: ' + p.owner + (p.budget_usd ? ' · ' + fmtMoney(num(p.budget_usd)) : '')) : null, h('div', { class: 'eyebrow' }, 'Goals'), h('ul', { class: 'small' }, arr(p.goals).map((x) => h('li', null, x))), h('div', { class: 'eyebrow' }, 'Deliverables'), h('ul', { class: 'small' }, arr(p.deliverables).map((x) => h('li', null, x))), h('div', { class: 'kill' }, h('strong', null, 'Kill criteria: '), arr(p.kill_criteria).length ? h('ul', null, arr(p.kill_criteria).map((x) => h('li', null, x))) : '—')); }))) },
  ];
  return h('div', { class: 'page' }, crumbs([{ text: 'Opportunities', href: '#opportunities' }, { text: id }]), pageHead(id + ' · Surviving opportunity', reg.title || c.title || id, c.problem || reg.problem, [verdictBadge(s.verdict), h('span', null, 'Market ', scorePill(s.market_attractiveness ?? 0)), h('span', null, 'Founder fit ', scorePill(s.founder_fit ?? 0)), stageChip(c.market_stage), ...arr(reg.categories).map((k) => chip(CATEGORY_NAMES[k] || k, 'cat'))]), tabs(tabDefs, tabIndexFor(tabDefs, r.sub)));
}

route('plan', () => {
  const ff = D.founderfit?.founder_fit || {};
  const top = arr(ff.ranking).slice(0, 3).map((x) => x.gap_id).filter((id) => D.survivors?.[id]?.gtm);
  const ids = top.length ? top : arr(D.survivorsOrder).slice(0, 3);
  const PHASES = [['weeks_1_3', 'Weeks 1–3', 'Research & customer interviews'], ['weeks_4_6', 'Weeks 4–6', 'Technical experiments'], ['weeks_7_9', 'Weeks 7–9', 'Prototype'], ['weeks_10_12', 'Weeks 10–12', 'User validation & demo']];
  return h('div', { class: 'page' },
    pageHead('Deliverable 10 · 90-day validation plans', 'Three plans, each with kill criteria', 'For the three most promising opportunities: what to research, build and demonstrate in twelve weeks, who owns each block, what it costs, and the measurable conditions under which the founders should stop.'),
    ids.length ? null : h('div', { class: 'callout amber' }, h('p', null, 'Stage status: 90-day plans are written for the three highest-ranked survivors once the red team, scoring and founder-fit stages complete. Until then, each registry gap page carries the MVP sketch, entry vehicle and killer risk proposed by the segment analyses.')),
    ids.length ? ids.map((id) => { const gtm = D.survivors[id].gtm; const plan = gtm.plan_90_days || {}; const reg = arr(D.registry?.gaps).find((g) => g.id === id) || {}; return card(h('div', { class: 'card-head' }, h('h2', null, h('a', { href: '#opportunities/' + id + '/90-day-plan' }, id + ' · ' + (reg.title || id))), plan.total_budget_usd ? chip('Total ' + fmtMoney(num(plan.total_budget_usd)), 'amber') : null), h('div', { class: 'plan' }, PHASES.map(([k, w, label]) => { const p = plan[k] || {}; return h('div', { class: 'phase' }, h('h4', null, w), h('div', { class: 'eyebrow' }, label), p.owner ? h('div', { class: 'small muted' }, 'Owner: ' + p.owner + (p.budget_usd ? ' · ' + fmtMoney(num(p.budget_usd)) : '')) : null, h('ul', { class: 'small' }, arr(p.goals).map((x) => h('li', null, x))), arr(p.deliverables).length ? h('div', { class: 'small' }, h('b', null, 'Deliverables: '), arr(p.deliverables).join('; ')) : null, h('div', { class: 'kill' }, h('strong', null, 'Kill if: '), arr(p.kill_criteria).length ? h('ul', null, arr(p.kill_criteria).map((x) => h('li', null, x))) : '—')); })), gtm.most_important_question?.milestone_for_next_2_5m ? h('p', { class: 'small', style: { marginTop: '10px' } }, h('b', null, 'Milestone for the next $2–5M: '), gtm.most_important_question.milestone_for_next_2_5m) : null); }) : empty('No plans recorded.'));
});

route('founderfit', () => {
  const ff = D.founderfit || {}; const f = ff.founder_fit || {};
  const reg = arr(D.regulatoryMatrix);
  return h('div', { class: 'page' },
    pageHead('Deliverables 8 & 9 · Founder fit', 'Which opportunities two founders and ~$250k can actually reach', 'Not whether $250k can build the company, but whether it can reach the next fundable milestone: a demonstration or customer validation credible enough to raise institutional capital or win government funding.'),
    f.team_constraints_summary ? h('div', { class: 'callout amber' }, h('div', { class: 'eyebrow' }, 'Team constraints'), h('p', null, f.team_constraints_summary)) : (ff.founder_fit ? null : h('div', { class: 'callout amber' }, h('p', null, 'Stage status: the ranked founder-fit analysis and opportunity matrix are produced after scoring. The regulatory matrix and the founder-specific analysis below come from the completed regulatory evidence sweep.'))),
    f.portfolio ? card('Recommended portfolio', kv([['Primary bet', f.portfolio.primary], ['Secondary bet', f.portfolio.secondary], ['Option', f.portfolio.option], ['Rationale', f.portfolio.rationale]])) : null,
    arr(f.ranking).length ? card('Ranking', h('div', { class: 'stack' }, arr(f.ranking).map((x) => fold(h('span', null, h('b', null, '#' + x.rank + ' '), h('a', { href: '#opportunities/' + x.gap_id }, x.gap_id + ' ' + (x.title || '')), ' ', chip(x.reaches_fundable_milestone_in_12_months ? String(x.reaches_fundable_milestone_in_12_months).slice(0, 40) : '—', /^yes/i.test(x.reaches_fundable_milestone_in_12_months) ? 'good' : /^no/i.test(x.reaches_fundable_milestone_in_12_months) ? 'bad' : 'warn')), kv([['Reaches a fundable milestone in 12 months?', x.reaches_fundable_milestone_in_12_months], ['Milestone', x.milestone], ['Evidence produced', x.evidence_produced], ['Who would fund', val(x.who_would_fund, { chips: true })], ['Team risks', val(x.team_risks)], ['Mitigations', val(x.mitigations)], ['Needs counsel', val(x.needs_counsel)]]), x.rank <= 3)))) : null,
    arr(f.do_not_do).length ? card('What the founders should not do', h('ul', null, arr(f.do_not_do).map((x) => h('li', null, isStr(x) ? x : val(x))))) : null,
    ff.opportunity_matrix ? card('Opportunity matrix', opportunityMatrix(ff.opportunity_matrix)) : null,
    arr(ff.most_important_question_top3).length ? card('The most important question, top three', h('div', { class: 'stack' }, arr(ff.most_important_question_top3).map((x) => h('div', null, h('h4', null, h('a', { href: '#opportunities/' + x.gap_id }, x.gap_id + ' ' + (arr(D.registry?.gaps).find((g) => g.id === x.gap_id)?.title || ''))), h('div', { class: 'prose' }, h('p', null, x.answer)))))) : null,
    reg.length ? card('Regulatory burden by segment (market-analysis level, not legal advice)', h('p', { class: 'small muted' }, 'Rows come from the regulatory evidence sweep and were mapped onto the canonical segments. Expand a row for the full assessment.'), dataTable(reg, [{ key: 'segment_id', title: 'Segment', render: (r) => h('div', null, h('a', { class: 'mono', href: '#segments/' + r.segment_id }, r.segment_id), h('span', { class: 'cell-sub' }, r.segment_name || r.assumed_segment_label || '')), width: '160px' }, { key: 'regulatory_burden', title: 'Burden', render: (r) => chip(r.regulatory_burden || '—', /high/i.test(r.regulatory_burden) ? 'bad' : /med/i.test(r.regulatory_burden) ? 'warn' : 'good') }, { key: 'classification_dependence', title: 'Classification', render: (r) => chip(r.classification_dependence || '—', /immed/i.test(r.classification_dependence) ? 'bad' : /event/i.test(r.classification_dependence) ? 'warn' : 'good') }, { key: 'mvp_unclassified_commercial', title: 'Unclassified MVP?', render: (r) => chip(r.mvp_unclassified_commercial || '—', /^yes/i.test(r.mvp_unclassified_commercial) ? 'good' : /partial/i.test(r.mvp_unclassified_commercial) ? 'warn' : 'bad') }, { key: 'likely_export_status_of_mvp', title: 'Likely export status of MVP', render: (r) => h('span', { class: 'small' }, r.likely_export_status_of_mvp || '—') }, { key: 'details', title: 'Details', render: (r) => fold('Full row', h('dl', { class: 'kv' }, Object.entries(r).filter(([k]) => !['segment_id', 'segment_name', 'original_segment_id', 'assumed_segment_label', 'regulatory_burden', 'classification_dependence', 'mvp_unclassified_commercial', 'likely_export_status_of_mvp', '__t'].includes(k)).map(([k, v]) => [h('dt', null, titleCase(k)), h('dd', null, val(v))]))) }], { filterable: false, pageSize: 20 })) : null,
    D.founderAnalysis ? card('Founder-specific regulatory analysis', h('p', { class: 'small muted' }, 'Descriptive only. Every item flagged "needs counsel" should go to export-control, immigration and government-contracts lawyers before a business model is fixed.'), val(D.founderAnalysis)) : null,
    arr(ff.contradictions_noted).length ? fold('Contradictions noted between files', val(ff.contradictions_noted)) : null,
    sourceList(ff.sources));
});

route('whitespace', (r) => {
  const w = D.whitespace || {}; const m = w.matrix || D.whitespaceInput || {};
  const tested = !!(D.whitespace && D.whitespace.matrix);
  const chain = arr(m.chain).length ? m.chain : ['COLLECT', 'TRANSPORT', 'PROCESS', 'FUSE', 'DECIDE', 'DISSEMINATE_TASK'];
  const ech = arr(m.echelons).length ? m.echelons : ['individual_platform', 'tactical_unit', 'battalion_brigade', 'division_corps', 'theater', 'joint', 'coalition'];
  const cells = arr(m.cells);
  const cellOf = (x, y) => cells.find((c) => c.chain === x && c.echelon === y);
  const detail = h('div', { class: 'stack' });
  const showCell = (x, y) => { const c = cellOf(x, y) || { companies: [] }; detail.innerHTML = ''; detail.append(card(h('div', { class: 'card-head' }, h('h3', null, titleCase(x) + ' × ' + titleCase(y)), c.density ? chip(c.density, c.density === 'crowded' ? 'amber' : c.density === 'empty' ? 'outline' : 'accent') : null, c.test_verdict ? chip('Test: ' + c.test_verdict, /under/i.test(c.test_verdict) ? 'good' : 'outline') : null), kv([['Companies (' + arr(c.companies).length + ')', h('div', { class: 'chips' }, arr(c.companies).map((n) => { const cc = findCompany(n); return cc ? h('a', { class: 'chip accent', href: '#companies/' + cc.slug }, n) : chip(n); }))], ['Dominant players', val(c.dominant, { chips: true })], ['Rationale', c.rationale], ['Linked gaps', arr(c.linked_gap_ids).length ? h('div', { class: 'chips' }, arr(c.linked_gap_ids).map((gid) => h('a', { class: 'chip mono', href: '#gaps/' + gid }, gid))) : '—'], ['Confidence', confTag(c.confidence) || '—']]))); };
  const grid = heatmap(chain, ech, (x, y) => { const c = cellOf(x, y); const n = c ? (c.count ?? arr(c.companies).length) : 0; return { value: n, label: String(n), tip: `<b>${esc(titleCase(x))} × ${esc(titleCase(y))}</b><br>${n} companies${c && c.test_verdict ? '<br>Test: ' + esc(c.test_verdict) : ''}`, onClick: (el) => { $$('.heat .cell.active').forEach((e) => e.classList.remove('active')); el.classList.add('active'); showCell(x, y); } }; }, { xLabel: (x) => titleCase(x).replace('Disseminate Task', 'Disseminate / Task'), yLabel: (y) => titleCase(y).replace('Individual Platform', 'Individual / platform').replace('Battalion Brigade', 'Battalion / brigade').replace('Division Corps', 'Division / corps') });
  const under = cells.filter((c) => /under/i.test(c.test_verdict));
  if (cells.length) showCell(chain[3], ech[2]);
  return h('div', { class: 'page' },
    pageHead('Deliverable · Competitive white-space map', 'Where the companies sit, and what the empty cells really mean', 'X axis: the information chain. Y axis: operating echelon. Darker cells hold more companies. Every empty or sparse cell was tested rather than assumed to be an opportunity: it may mean no demand, classification, impossible economics, government-only capability, or a market too small.'),
    w.summary ? h('div', { class: 'callout' }, h('p', null, w.summary)) : (tested ? null : h('div', { class: 'callout amber' }, h('p', null, 'Interim view: cell counts come from the company records and segment analyses (84 companies placed by chain step and echelon). The empty-cell test, which decides whether a sparse cell means no demand, classification, impossible economics, government-only capability or a genuine under-served niche, runs in the synthesis stage.'))),
    card('Company density', h('div', { style: { overflowX: 'auto' } }, grid), h('p', { class: 'small muted' }, 'Click a cell for the companies in it and the test verdict.')),
    detail,
    under.length ? card('Cells judged under-served (with evidence of demand)', dataTable(under, [{ key: 'chain', title: 'Chain step', render: (c) => titleCase(c.chain) }, { key: 'echelon', title: 'Echelon', render: (c) => titleCase(c.echelon) }, { key: 'rationale', title: 'Rationale' }, { key: 'linked_gap_ids', title: 'Linked gaps', render: (c) => h('div', { class: 'chips' }, arr(c.linked_gap_ids).map((gid) => h('a', { class: 'chip mono', href: '#gaps/' + gid }, gid))) }, { key: 'confidence', title: 'Conf.', render: (c) => confTag(c.confidence) || '—' }], { filterable: false })) : null,
    cells.length ? fold('All cells (table view)', dataTable(cells, [{ key: 'chain', title: 'Chain', render: (c) => titleCase(c.chain) }, { key: 'echelon', title: 'Echelon', render: (c) => titleCase(c.echelon) }, { key: 'count', title: 'Count', num: true, render: (c) => String(c.count ?? arr(c.companies).length) }, { key: 'density', title: 'Density' }, { key: 'test_verdict', title: 'Test verdict' }, { key: 'dominant', title: 'Dominant', render: (c) => chips(c.dominant) }, { key: 'rationale', title: 'Rationale' }], { filterable: false, pageSize: 50 })) : null,
    arr(w.corrections).length ? fold('Placement corrections made during the test', dataTable(arr(w.corrections), [{ key: 'company', title: 'Company' }, { key: 'from', title: 'From' }, { key: 'to', title: 'To' }, { key: 'why', title: 'Why' }], { filterable: false })) : null,
    sourceList(w.sources));
});
