/* ===================== Views: segments ===================== */
const STAGE_CLASS = { emerging: 'accent', prototyping: 'amber', transitioning: 'good', mature: 'outline', stagnant: 'bad' };
function stageChip(stage) { if (!stage) return null; const k = String(stage).toLowerCase(); const cls = Object.keys(STAGE_CLASS).find((s) => k.startsWith(s)); return chip(stage, STAGE_CLASS[cls] || 'outline'); }

route('segments', (r) => {
  if (r.id) return segmentDetail(r);
  const segs = arr(D.segments);
  return h('div', { class: 'page' },
    pageHead('Deliverable 5 · Segment deep dives', 'Fourteen C4ISR segments', 'Each chapter maps what the layer does, who uses and buys it, the current architecture, incumbents and startups, government programs and contracts, technical difficulty, capital intensity, regulatory access, documented pain, why it is still unsolved, market stage, and the candidate gaps proposed for red-teaming.'),
    h('div', { class: 'grid cols-3' }, segs.map((s) => h('a', { class: 'seg-card', href: '#segments/' + s.segment_id }, h('div', { class: 'row' }, h('span', { class: 'seg-id' }, s.segment_id), stageChip(s.market_stage?.stage)), h('h3', null, s.segment_name), h('div', { class: 'seg-sum' }, (s.attractiveness?.verdict || s.what_it_does || '').slice(0, 220)), h('div', { class: 'row small muted' }, arr(s.candidate_gaps).length + ' candidate gaps · ' + arr(s.startups).length + ' startups · ' + arr(s.contracts).length + ' contracts')))));
});

function segmentDetail(r) {
  const s = arr(D.segments).find((x) => x.segment_id === r.id);
  if (!s) return h('div', { class: 'page' }, crumbs([{ text: 'Segments', href: '#segments' }]), empty('Unknown segment.'));
  const regGaps = (D.registry?.gaps || []).filter((g) => arr(g.segment_ids).includes(s.segment_id) || arr(g.merged_from).some((m) => m.startsWith(s.segment_id + '-')));
  const cos = arr(D.companies).filter((c) => arr(c.segment_ids).includes(s.segment_id));
  const tabDefs = [
    { title: 'Overview', render: () => h('div', { class: 'stack' },
      card('What this layer does', h('p', null, s.what_it_does)),
      arr(s.sub_taxonomy).length ? card('Sub-taxonomy', h('div', { class: 'table-wrap' }, h('table', { class: 'data' }, h('thead', null, h('tr', null, h('th', null, 'Sub-segment'), h('th', null, 'Note'))), h('tbody', null, arr(s.sub_taxonomy).map((t) => h('tr', null, h('td', null, t.name), h('td', null, t.note || '—'))))))) : null,
      h('div', { class: 'grid cols-2' },
        card('Users', arr(s.users).length ? h('div', { class: 'table-wrap' }, h('table', { class: 'data' }, h('thead', null, h('tr', null, h('th', null, 'Role'), h('th', null, 'Echelon'), h('th', null, 'What they do'))), h('tbody', null, arr(s.users).map((u) => h('tr', null, h('td', null, u.role), h('td', null, u.echelon || '—'), h('td', null, u.what_they_do || '—')))))) : empty()),
        card('Buyers', arr(s.buyers).length ? h('div', { class: 'table-wrap' }, h('table', { class: 'data' }, h('thead', null, h('tr', null, h('th', null, 'Organization'), h('th', null, 'Service'), h('th', null, 'Role'), h('th', null, 'Note'))), h('tbody', null, arr(s.buyers).map((b) => h('tr', null, h('td', null, b.organization), h('td', null, b.service || '—'), h('td', null, b.role || '—'), h('td', null, b.note || '—')))))) : empty())),
      h('div', { class: 'grid cols-2' }, h('div', { class: 'callout bull' }, h('div', { class: 'eyebrow' }, 'Bull case'), h('p', null, s.attractiveness?.bull || '—')), h('div', { class: 'callout bear' }, h('div', { class: 'eyebrow' }, 'Bear case'), h('p', null, s.attractiveness?.bear || '—'))),
      s.attractiveness?.verdict ? h('div', { class: 'callout' }, h('div', { class: 'eyebrow' }, 'Verdict'), h('p', null, s.attractiveness.verdict)) : null) },
    { title: 'Architecture', render: () => { const a = s.current_architecture || {}; return h('div', { class: 'stack' }, card('Current architecture', h('p', null, a.description || '—'), kv([['Data formats / protocols', val(a.data_formats_protocols, { chips: true })], ['Security domain', a.security_domain], ['Connectivity dependency', a.connectivity_dependency], ['What breaks when disconnected', a.what_breaks_when_disconnected]])), card('Major systems', arr(a.major_systems).length ? dataTable(arr(a.major_systems), [{ key: 'name', title: 'System' }, { key: 'owner', title: 'Owner' }, { key: 'function', title: 'Function' }, { key: 'vendor', title: 'Vendor' }, { key: 'status', title: 'Status' }], { filterable: arr(a.major_systems).length > 10 }) : empty())); } },
    { title: 'Players', render: () => h('div', { class: 'stack' },
      card('Incumbents', arr(s.incumbents).length ? dataTable(arr(s.incumbents), [{ key: 'name', title: 'Company', render: (x) => companyLink(x.name) }, { key: 'products', title: 'Products' }, { key: 'position', title: 'Position' }], { filterable: false }) : empty()),
      card('Startups', arr(s.startups).length ? dataTable(arr(s.startups), [{ key: 'name', title: 'Company', render: (x) => companyLink(x.name) }, { key: 'product', title: 'Product' }, { key: 'funding', title: 'Funding' }, { key: 'traction_evidence', title: 'Traction evidence' }, { key: 'confidence', title: 'Conf.', render: (x) => confTag(x.confidence) || '—' }], { filterable: false }) : empty()),
      cos.length ? card('Company records tagged to this segment (' + cos.length + ')', h('div', { class: 'chips' }, cos.map((c) => h('a', { class: 'chip accent', href: '#companies/' + c.slug }, c.name)))) : null,
      arr(s.whitespace_placements).length ? fold('White-space placements (' + arr(s.whitespace_placements).length + ')', dataTable(arr(s.whitespace_placements), [{ key: 'company_or_product', title: 'Company / product' }, { key: 'chain_steps', title: 'Chain steps', render: (x) => chips(x.chain_steps, 'mono') }, { key: 'echelons', title: 'Echelons', render: (x) => chips(x.echelons, 'mono') }], { filterable: false })) : null) },
    { title: 'Programs & contracts', render: () => h('div', { class: 'stack' },
      card('Government programs', arr(s.government_programs).length ? dataTable(arr(s.government_programs), [{ key: 'name', title: 'Program' }, { key: 'owner', title: 'Owner' }, { key: 'description', title: 'Description' }, { key: 'status_2026', title: 'Status (2026)' }, { key: 'budget_evidence', title: 'Budget evidence' }, { key: 'source_url', title: 'Source', render: (x) => (x.source_url ? h('a', { href: x.source_url, target: '_blank', rel: 'noopener' }, shortUrl(x.source_url)) : '—') }], { filterable: arr(s.government_programs).length > 8 }) : empty()),
      card('Known contracts', h('p', { class: 'small muted' }, 'Ceiling is never revenue; a prototype award is never a scaled deployment. Obligated and awarded amounts are shown separately where the record allows.'), contractTable(s.contracts, { showVendor: true }))) },
    { title: 'Difficulty & capital', render: () => h('div', { class: 'stack' },
      card('Technical difficulty', kv([['Summary', s.technical_difficulty?.summary], ['Hardest problem', s.technical_difficulty?.hardest_problem], ['Commodity parts', s.technical_difficulty?.commodity_parts], ['Required expertise', val(s.technical_difficulty?.required_expertise, { chips: true })]])),
      card('Capital intensity', kv([['Proof of concept', s.capital_intensity?.proof_of_concept_usd], ['Credible military demo', s.capital_intensity?.credible_military_demo_usd], ['First production deployment', s.capital_intensity?.first_production_deployment_usd], ['Assumptions', s.capital_intensity?.assumptions]])),
      card('Expertise matrix', h('p', { class: 'small muted' }, 'Red = critical, amber = important, outline = optional.'), expertiseMatrix(s.expertise_matrix))) },
    { title: 'Regulatory', render: () => { const g = s.regulatory_access || {}; return card('Regulatory and access difficulty', h('div', { class: 'row', style: { marginBottom: '10px' } }, g.overall ? chip('Overall: ' + g.overall, /high/i.test(g.overall) ? 'bad' : /med/i.test(g.overall) ? 'warn' : 'good') : null), kv([['Prototype with commercial / unclassified data', g.prototype_with_commercial_unclassified_data], ['Government data required', g.government_data_required], ['ITAR / EAR', g.itar_ear], ['CUI likely', g.cui_likely], ['Classified integration eventually', g.classified_integration_eventually], ['Cleared personnel at MVP', g.cleared_personnel_at_mvp], ['Non-U.S.-person founder note', g.non_us_person_founder_note]])); } },
    { title: 'Pain & why unsolved', render: () => h('div', { class: 'stack' },
      card('Existing unsolved pain (evidence only)', evidenceList(arr(s.unsolved_pain).map((p) => ({ claim: p.pain + (p.evidence ? ' — ' + p.evidence : ''), source_url: p.source_url, pub_date: p.pub_date, label: p.label })))),
      card('Why hasn\'t it already been solved?', arr(s.why_not_solved).length ? h('dl', { class: 'kv' }, arr(s.why_not_solved).map((w) => [h('dt', null, w.reason), h('dd', null, w.explanation)])) : empty()),
      card('Exercise evidence', arr(s.exercise_evidence).length ? dataTable(arr(s.exercise_evidence), [{ key: 'exercise', title: 'Exercise' }, { key: 'year', title: 'Year' }, { key: 'quote_or_paraphrase', title: 'Pain (quote or paraphrase)' }, { key: 'pain_keywords', title: 'Keywords', render: (x) => chips(x.pain_keywords, 'mono') }, { key: 'source_url', title: 'Source', render: (x) => (x.source_url ? h('a', { href: x.source_url, target: '_blank', rel: 'noopener' }, shortUrl(x.source_url)) : '—') }], { filterable: false }) : empty())) },
    { title: 'Market stage', render: () => { const m = s.market_stage || {}; const pp = s.proto_purgatory || {}; return h('div', { class: 'stack' }, card(h('div', { class: 'card-head' }, h('h3', null, 'Procurement signal analysis'), stageChip(m.stage)), h('p', null, m.rationale || '—'), h('h4', { style: { margin: '12px 0 8px' } }, 'Signal sequence'), timeline(m.signal_sequence)), card(h('div', { class: 'card-head' }, h('h3', null, 'Proto-purgatory check'), chip(pp.observed ? 'Observed' : 'Not observed', pp.observed ? 'warn' : 'outline')), kv([['Notes', pp.notes], ['Opportunity or warning?', pp.opportunity_or_warning]]))); } },
    { title: 'Candidate gaps', render: () => h('div', { class: 'stack' },
      regGaps.length ? card('In the consolidated registry', h('div', { class: 'table-wrap' }, h('table', { class: 'data' }, h('thead', null, h('tr', null, h('th', null, 'ID'), h('th', null, 'Gap'), h('th', null, 'Verdict'), h('th', { class: 'num' }, 'Market'), h('th', { class: 'num' }, 'Fit'))), h('tbody', null, regGaps.map((g) => h('tr', { class: 'clickable', onclick: () => (location.hash = '#gaps/' + g.id) }, h('td', { class: 'mono' }, g.id), h('td', null, h('a', { href: '#gaps/' + g.id }, g.title)), h('td', null, verdictBadge(D.gaps?.[g.id]?.score?.verdict)), h('td', { class: 'num' }, scorePill(D.gaps?.[g.id]?.score?.market_attractiveness ?? 0)), h('td', { class: 'num' }, scorePill(D.gaps?.[g.id]?.score?.founder_fit ?? 0)))))))) : null,
      card('As proposed by the segment analysis (pre-consolidation)', arr(s.candidate_gaps).length ? h('div', { class: 'stack' }, arr(s.candidate_gaps).map((g) => fold(h('span', null, h('span', { class: 'mono muted' }, g.id + ' '), g.title, ' ', chips(g.categories, 'cat'), ' ', g.initial_attractiveness ? chip(g.initial_attractiveness, /high/i.test(g.initial_attractiveness) ? 'good' : /med/i.test(g.initial_attractiveness) ? 'warn' : 'outline') : null), h('div', { class: 'stack' }, kv([['Problem', g.problem_one_sentence], ['User', g.user], ['Current workflow', g.current_workflow], ['Current solution', g.current_solution], ['Failure point', g.failure_point], ['Why startups haven\'t solved it', g.why_startups_havent_solved], ['Companies near', val(g.companies_near, { chips: true })], ['Incumbent response risk', g.incumbent_response_risk], ['Technical wedge (hypothesis)', g.technical_wedge_hypothesis], ['MVP sketch', g.mvp_sketch], ['Data requirement', g.data_requirement], ['Integration requirement', g.integration_requirement], ['Entry vehicle', g.entry_vehicle], ['Why now', g.why_now], ['Killer risk', g.killer_risk], ['Confidence', confTag(g.confidence) || '—']]), h('h4', null, 'Evidence'), evidenceList(g.evidence))))) : empty())) },
    { title: 'Search log', render: () => h('div', { class: 'stack' }, card('Saturation statement', h('p', null, s.saturation_statement || '—')), fold('Queries run (' + arr(s.search_log).length + ')', h('ul', { class: 'small' }, arr(s.search_log).map((q) => h('li', null, (q.useful ? '✓ ' : '· ') + (q.query || q))))), sourceList(s.sources)) },
  ];
  return h('div', { class: 'page' }, crumbs([{ text: 'Segments', href: '#segments' }, { text: s.segment_id }]), pageHead(s.segment_id + ' · Segment deep dive', s.segment_name, null, [stageChip(s.market_stage?.stage), s.regulatory_access?.overall ? chip('Regulatory ' + s.regulatory_access.overall, 'outline') : null, chip(arr(s.candidate_gaps).length + ' candidate gaps', 'outline'), chip(arr(s.sources).length + ' sources', 'mono')]), tabs(tabDefs, tabIndexFor(tabDefs, r.sub)));
}
function tabIndexFor(defs, sub) { if (!sub) return 0; const i = defs.findIndex((d) => slug(d.title) === slug(sub)); return i < 0 ? 0 : i; }
function companyLink(name) { if (!name) return '—'; const c = findCompany(name); return c ? h('a', { href: '#companies/' + c.slug }, name) : h('span', null, name); }
function findCompany(name) { const n = String(name).toLowerCase(); return arr(D.companies).find((c) => c.name.toLowerCase() === n) || arr(D.companies).find((c) => n.includes(c.name.toLowerCase().split(' (')[0]) || c.name.toLowerCase().includes(n.split(' (')[0])); }
