/**
 * src/lib/ui/assets.ts for the single-file build: every asset is embedded as a data URL (virtual:piste/assets,
 * generated by build.mjs from src/assets).
 */
import { ASSETS } from 'virtual:piste/assets'

export const ASSET_FILES = ['greek-peak-hero.webp', 'greek-peak-duo.webp', 'greek-peak-ridge.svg', 'matterhorn-cut.webp', 'matterhorn-duo.webp', 'matterhorn-ridge.svg', 'skier-body.glb'] as const
export type AssetFile = (typeof ASSET_FILES)[number]

export function assetUrl(file: AssetFile): string {
  return ASSETS[file] ?? ''
}
