/**
 * Modules generated by standalone/build.mjs at bundle time (esbuild plugin "piste-virtual").
 * They exist only inside the single-file bundle; TypeScript sees these declarations.
 */

declare module 'virtual:piste/routes' {
  /** Loose shape of a route module (page / layout / loading / error / not-found) as the bundler imports it. */
  export interface RouteModule {
    default?: unknown
    metadata?: { title?: unknown; description?: string }
    generateMetadata?: (props: {
      params: Promise<Record<string, string>>
      searchParams: Promise<Record<string, string | string[]>>
    }) => Promise<{ title?: unknown }> | { title?: unknown }
    viewport?: unknown
  }

  /** One directory under src/app. Route groups `(x)` consume no URL segment; `[x]` consumes one as a param. */
  export interface RouteNodeDef {
    segment: string
    kind: 'root' | 'static' | 'group' | 'dynamic' | 'catch-all'
    param?: string
    layout?: RouteModule
    page?: RouteModule
    loading?: RouteModule
    error?: RouteModule
    notFound?: RouteModule
    /** Which of this node's files start with 'use client' (rendered as components, never called as functions). */
    client?: Partial<Record<'layout' | 'page' | 'loading' | 'error' | 'notFound', boolean>>
    children: RouteNodeDef[]
  }

  export interface ApiRouteDef {
    /** e.g. /api/export/csv */
    path: string
    module: Record<string, unknown>
  }

  export const tree: RouteNodeDef
  export const apiRoutes: ApiRouteDef[]
}

declare module 'virtual:piste/files' {
  /** Read-only files served by the node:fs shim (the curated catalog), keyed by POSIX path relative to the project root. */
  export const files: Record<string, string>
}

declare module 'virtual:piste/migrations' {
  export interface EmbeddedMigration {
    tag: string
    /** drizzle journal `when` (folderMillis) */
    when: number
    /** sha256 of the SQL file, exactly as drizzle's migrator computes it */
    hash: string
    statements: string[]
  }
  export const migrations: EmbeddedMigration[]
}

declare module 'virtual:piste/build-info' {
  export const BUILD_INFO: {
    builtAt: string
    /** Short id of the embedded migrations; a stored database with another id needs the recovery screen. */
    schemaId: string
    /** Hash of the embedded catalog files; a change re-runs the (idempotent) catalog seed on the live database. */
    catalogHash: string
  }
}

declare module 'virtual:piste/maplibre-worker' {
  const source: string
  export default source
}

declare module '*.wasm' {
  const bytes: Uint8Array
  export default bytes
}

declare module 'maplibre-gl/dist/maplibre-gl.mjs' {
  export * from 'maplibre-gl'
}
